### ISSUE TITLE
Feature request: compile time error, when too many args are given

### ISSUE THREAD

**Issue by strasdat** [fmtlib/fmt#1241] opened 2019-07-21 18:52 UTC
``fmt::format(fmt("{:s}"))`` currently leads to ``"argument index out of range"``.

However, ``fmt::format(fmt("{:s}"), "foo", "bar")`` currently compiles just fine. IMO, that should fail to compile as well.

**Comment by vitaut** [comment] 2019-07-22 09:50
Duplicate of #492

**Closed by vitaut** 2019-07-22 09:50 UTC
