### ISSUE TITLE
Warnings when compiling on windows: stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future

### ISSUE THREAD

**Issue by alexander-riss** [fmtlib/fmt#3896] opened 2024-03-15 19:04 UTC
warning C4996: 'stdext::checked_array_iterator<T *>': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.

Would probably make sense to add a gsl::span switch for windows while min cpp version is still below cpp20?

**Comment by vitaut** [comment] 2024-03-19 01:52
Looks like a duplicate of #3540.

**Closed by vitaut** 2024-03-19 01:52 UTC
