### ISSUE TITLE
__int128 is not supported in armeabi-v7a

### ISSUE THREAD

**Issue by Yancey2023** [fmtlib/fmt#4140] opened 2024-09-01 06:08 UTC
```log
Execution failed for task ':app:buildCMakeRelWithDebInfo[armeabi-v7a]'.
> com.android.ide.common.process.ProcessException: ninja: Entering directory `D:\AS\project\CHelper-Android\app\.cxx\RelWithDebInfo\621a2d23\armeabi-v7a'
  [1/74] Building CXX object include/fmt/CMakeFiles/fmt.dir/src/os.cc.o
  FAILED: include/fmt/CMakeFiles/fmt.dir/src/os.cc.o 
  D:\AS\sdk\ndk\27.0.12077973\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=armv7-none-linux-androideabi24 --sysroot=D:/AS/sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/windows-x86_64/sysroot  -ID:/AS/project/CHelper-Android/app/src/main/cpp/CHelper-Core/CHelper-Core/include/fmt/include -ID:/AS/project/CHelper-Android/app/src/main/cpp/CHelper-Core/CHelper-Android/../CHelper-Core/include/hedley/include -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security   -O2 -g -DNDEBUG -fPIC -std=gnu++17 -MD -MT include/fmt/CMakeFiles/fmt.dir/src/os.cc.o -MF include\fmt\CMakeFiles\fmt.dir\src\os.cc.o.d -o include/fmt/CMakeFiles/fmt.dir/src/os.cc.o -c D:/AS/project/CHelper-Android/app/src/main/cpp/CHelper-Core/CHelper-Core/include/fmt/src/os.cc
  In file included from D:/AS/project/CHelper-Android/app/src/main/cpp/CHelper-Core/CHelper-Core/include/fmt/src/os.cc:13:
  In file included from D:/AS/project/CHelper-Android/app/src/main/cpp/CHelper-Core/CHelper-Core/include/fmt/include/fmt/os.h:11:
  In file included from D:/AS/project/CHelper-Android/app/src/main/cpp/CHelper-Core/CHelper-Core/include/fmt/include/fmt/format.h:41:
  D:/AS/project/CHelper-Android/app/src/main/cpp/CHelper-Core/CHelper-Core/include/fmt/include/fmt/base.h:462:59: error: __int128 is not supported on this target
    462 |   using format_type = conditional_t<(N <= 64), long long, __int128>;
        |                                                           ^
  D:/AS/project/CHelper-Android/app/src/main/cpp/CHelper-Core/CHelper-Core/include/fmt/include/fmt/base.h:467:61: error: __int128 is not supported on this target
    467 |       conditional_t<(N <= 64), unsigned long long, unsigned __int128>;
        |                                                             ^
  2 errors generated.
  [2/74] Building CXX object include/fmt/CMakeFiles/fmt.dir/src/format.cc.o
  FAILED: include/fmt/CMakeFiles/fmt.dir/src/format.cc.o 
  D:\AS\sdk\ndk\27.0.12077973\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=armv7-none-linux-androideabi24 --sysroot=D:/AS/sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/windows-x86_64/sysroot  -ID:/AS/project/CHelper-Android/app/src/main/cpp/CHelper-Core/CHelper-Core/include/fmt/include -ID:/AS/project/CHelper-Android/app/src/main/cpp/CHelper-Core/CHelper-Android/../CHelper-Core/include/hedley/include -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security   -O2 -g -DNDEBUG -fPIC -std=gnu++17 -MD -MT include/fmt/CMakeFiles/fmt.dir/src/format.cc.o -MF include\fmt\CMakeFiles\fmt.dir\src\format.cc.o.d -o include/fmt/CMakeFiles/fmt.dir/src/format.cc.o -c D:/AS/project/CHelper-Android/app/src/main/cpp/CHelper-Core/CHelper-Core/include/fmt/src/format.cc
  In file included from D:/AS/project/CHelper-Android/app/src/main/cpp/CHelper-Core/CHelper-Core/include/fmt/src/format.cc:8:
  In file included from D:/AS/project/CHelper-Android/app/src/main/cpp/CHelper-Core/CHelper-Core/include/fmt/include/fmt/format-inl.h:23:
  In file included from D:/AS/project/CHelper-Android/app/src/main/cpp/CHelper-Core/CHelper-Core/include/fmt/include/fmt/format.h:41:
  D:/AS/project/CHelper-Android/app/src/main/cpp/CHelper-Core/CHelper-Core/include/fmt/include/fmt/base.h:462:59: error: __int128 is not supported on this target
    462 |   using format_type = conditional_t<(N <= 64), long long, __int128>;
        |                                                           ^
  D:/AS/project/CHelper-Android/app/src/main/cpp/CHelper-Core/CHelper-Core/include/fmt/include/fmt/base.h:467:61: error: __int128 is not supported on this target
    467 |       conditional_t<(N <= 64), unsigned long long, unsigned __int128>;
        |                                                             ^
  2 errors generated.
  [3/74] Building CXX object CMakeFiles/CHelperAndroid.dir/cmake_pch.hxx.pch
  FAILED: CMakeFiles/CHelperAndroid.dir/cmake_pch.hxx.pch 
  D:\AS\sdk\ndk\27.0.12077973\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=armv7-none-linux-androideabi24 --sysroot=D:/AS/sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/windows-x86_64/sysroot -DCHelperAndroid=true -DCHelperAndroid_EXPORTS -ID:/AS/project/CHelper-Android/app/src/main/cpp/CHelper-Core/CHelper-Android/../CHelper-Core/include/hedley/include -ID:/AS/project/CHelper-Android/app/src/main/cpp/CHelper-Core/CHelper-Android/../CHelper-Core/include/pch -ID:/AS/project/CHelper-Android/app/src/main/cpp/CHelper-Core/CHelper-Android/../CHelper-Core/include/chelper -ID:/AS/project/CHelper-Android/app/.cxx/RelWithDebInfo/621a2d23/armeabi-v7a/include -ID:/AS/project/CHelper-Android/app/src/main/cpp/CHelper-Core/CHelper-Core/include/fmt/include -ID:/AS/project/CHelper-Android/app/src/main/cpp/CHelper-Core/CHelper-Core/include/json/include -ID:/AS/project/CHelper-Android/app/src/main/cpp/CHelper-Core/CHelper-Core/include/utfcpp/source -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security   -O2 -g -DNDEBUG -fPIC -std=gnu++17 -Winvalid-pch -fpch-instantiate-templates -Xclang -emit-pch -Xclang -include -Xclang D:/AS/project/CHelper-Android/app/.cxx/RelWithDebInfo/621a2d23/armeabi-v7a/CMakeFiles/CHelperAndroid.dir/cmake_pch.hxx -x c++-header -MD -MT CMakeFiles/CHelperAndroid.dir/cmake_pch.hxx.pch -MF CMakeFiles\CHelperAndroid.dir\cmake_pch.hxx.pch.d -o CMakeFiles/CHelperAndroid.dir/cmake_pch.hxx.pch -c D:/AS/project/CHelper-Android/app/.cxx/RelWithDebInfo/621a2d23/armeabi-v7a/CMakeFiles/CHelperAndroid.dir/cmake_pch.hxx.cxx
  In file included from <built-in>:1:
  In file included from D:/AS/project/CHelper-Android/app/.cxx/RelWithDebInfo/621a2d23/armeabi-v7a/CMakeFiles/CHelperAndroid.dir/cmake_pch.hxx:5:
  In file included from D:/AS/project/CHelper-Android/app/src/main/cpp/CHelper-Core/CHelper-Android/../CHelper-Core/include/pch/pch.h:68:
  In file included from D:/AS/project/CHelper-Android/app/src/main/cpp/CHelper-Core/CHelper-Core/include/fmt/include/fmt/color.h:11:
  In file included from D:/AS/project/CHelper-Android/app/src/main/cpp/CHelper-Core/CHelper-Core/include/fmt/include/fmt/format.h:41:
  D:/AS/project/CHelper-Android/app/src/main/cpp/CHelper-Core/CHelper-Core/include/fmt/include/fmt/base.h:462:59: error: __int128 is not supported on this target
    462 |   using format_type = conditional_t<(N <= 64), long long, __int128>;
        |                                                           ^
  D:/AS/project/CHelper-Android/app/src/main/cpp/CHelper-Core/CHelper-Core/include/fmt/include/fmt/base.h:467:61: error: __int128 is not supported on this target
    467 |       conditional_t<(N <= 64), unsigned long long, unsigned __int128>;
        |                                                             ^
  2 errors generated.
  ninja: build stopped: subcommand failed.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
BUILD FAILED in 1m 19s
89 actionable tasks: 22 executed, 67 up-to-date
```

**Comment by JingMatrix** [comment] 2024-09-01 08:51
You may set `FMT_USE_BITINT=0` to solve the problem

See exmaple here: https://github.com/JingMatrix/LSPosed/pull/13/files

**Comment by vitaut** [comment] 2024-09-01 13:51
`FMT_USE_INT128`, not `FMT_USE_BITINT` but we should improve `__int128_t` detection.

**Comment by Yancey2023** [comment] 2024-09-01 15:13
Thanks for your reply. I will try it.

**Comment by vitaut** [comment] 2024-09-03 03:13
Actually, @JingMatrix was right. The error is caused by an unconditional use of `__int128` in `_BitInt` code.

**Comment by vitaut** [comment] 2024-09-03 18:33
Fixed in https://github.com/fmtlib/fmt/commit/894b71da853f23364660de204a09b78fa42fab7b. Thanks for reporting.

**Closed by vitaut** 2024-09-03 18:33 UTC
