### ISSUE TITLE
Cygwin Compatibility

### ISSUE THREAD

**Issue by ixokai** [fmtlib/fmt#388] opened 2016-09-26 21:04 UTC
Hi. I ran into two compatibility issues with using fmt in a cygwin (gcc 5.4.0 64-bit) environment.

1) Apparently, when using c++11, gcc goes into strict mode and doesn't include any functions that aren't part of the standard. In particular, fdopen was an issue. Some googling told me you can include POSIX functions by #defining the following in posixc.c before any headers are imported:

#define _POSIX_C_SOURCE 200809L

I'm not quite sure if this is actually cygwin specific or not, as this seems to be gcc -- but I'm not in a position to test on linux yet.

2) Cygwin doesn't provide strtod_l, so I disabled FMT_LOCALE and then fmt compiled and worked.

**Comment by vitaut** [comment] 2016-09-27 13:31
I think you can workaround the first issue by adding a check for cygwin here:

```c++
#ifdef __MINGW32__
// Workaround MinGW bug https://sourceforge.net/p/mingw/bugs/2024/.
# undef __STRICT_ANSI__
#endif
```

in https://github.com/fmtlib/fmt/blob/master/fmt/posix.h#L13.

Could you submit the PR for this and the locale fix?

**Comment by vitaut** [comment] 2016-10-02 04:33
Should be fixed in #388, but I don't have a Windows machine to test. @ixokai, does it work for you?

**Comment by vitaut** [comment] 2016-10-04 13:17
Closing for now but feel free to reopen if you still get errors.

**Closed by vitaut** 2016-10-04 13:17 UTC

**Comment by speth** [comment] 2016-10-22 03:05
I can confirm that this works, using G++ 5.4.0 on Cygwin. Any chance of getting a 3.0.x bugfix release or branch with this at some point (esp. since `master` contains backwards-incompatible changes like moving things to `printf.h`).

**Comment by vitaut** [comment] 2016-10-22 03:38
I plan to make a new release but only after completing the first draft of the standard proposal. Hopefully it won't take long but I don't have any specific dates as I work on this in my spare time (which was a bit limited lately because of switching to a new job). If you or anyone else (with reasonable github history =)) are willing to spend some time on preparing a new release, I'll be happy to give write permissions to the repo.

**Comment by vitaut** [comment] 2016-10-22 13:39
Hey, @foonathan. There were a few requests for a new minor release of `fmt`, so if you are still interested in helping out, I can give you write permissions. Thanks!

**Comment by vitaut** [comment] 2016-10-22 14:15
Basically it will require creating a new branch from version 3.0, picking and merging bug fixes that don't break API from https://github.com/fmtlib/fmt/compare/3.0.0...master and listing them in https://github.com/fmtlib/fmt/blob/master/ChangeLog.rst under the new entry (3.0.1). Then the `support/manage.py` script can be used to publish the release. Not the most exciting work ever =), but very important as the current release is missing some critical fixes right now.

**Comment by foonathan** [comment] 2016-10-22 14:18
Alright I can do that. What about other issues?

**Comment by vitaut** [comment] 2016-10-22 14:33
Thanks! I've added you to the list of collaborators with write permissions so you should receive a confirmation shortly.

Right now release is the most important thing, but if you are feeling adventurous =) feel free to pick up any issue from https://github.com/fmtlib/fmt/issues. Any contribution is welcome!

**Comment by foonathan** [comment] 2016-10-22 21:09
Okay, I'll see what I can do tomorrow.
