### ISSUE TITLE
Undefined POSIX macro on MacOS 

### ISSUE THREAD

**Issue by VictorEijkhout** [fmtlib/fmt#3823] opened 2024-01-21 15:10 UTC
```
[  2%] Building CXX object test/gtest/CMakeFiles/gtest.dir/gmock-gtest-all.cc.o
/opt/local/bin/g++-mp-13 -DFMT_LIB_EXPORT -Dfmt_EXPORTS -I/Users/eijkhout/Installation/fmtlib/fmtlib-10.2.1/include -O3 -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk -mmacosx-version-min=13.0 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -MD -MT CMakeFiles/fmt.dir/src/format.cc.o -MF CMakeFiles/fmt.dir/src/format.cc.o.d -o CMakeFiles/fmt.dir/src/format.cc.o -c /Users/eijkhout/Installation/fmtlib/fmtlib-10.2.1/src/format.cc
cd /Users/eijkhout/Installation/fmtlib/build-10.2.1-macbookair-gcc13/test/gtest && /opt/local/bin/g++-mp-13 -DGTEST_HAS_STD_WSTRING=1 -D_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING=1 -isystem /Users/eijkhout/Installation/fmtlib/fmtlib-10.2.1/test/gtest/. -O3 -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk -mmacosx-version-min=13.0 -fvisibility=hidden -fvisibility-inlines-hidden -MD -MT test/gtest/CMakeFiles/gtest.dir/gmock-gtest-all.cc.o -MF CMakeFiles/gtest.dir/gmock-gtest-all.cc.o.d -o CMakeFiles/gtest.dir/gmock-gtest-all.cc.o -c /Users/eijkhout/Installation/fmtlib/fmtlib-10.2.1/test/gtest/gmock-gtest-all.cc
/Users/eijkhout/Installation/fmtlib/fmtlib-10.2.1/test/gtest/gmock-gtest-all.cc: In static member function 'static testing::internal::FilePath testing::internal::FilePath::GetCurrentDir()':
/Users/eijkhout/Installation/fmtlib/fmtlib-10.2.1/test/gtest/gmock-gtest-all.cc:9926:26: error: '_POSIX_PATH_MAX' was not declared in this scope
 9926 | # define GTEST_PATH_MAX_ _POSIX_PATH_MAX
      |                          ^~~~~~~~~~~~~~~
/Users/eijkhout/Installation/fmtlib/fmtlib-10.2.1/test/gtest/gmock-gtest-all.cc:9976:12: note: in expansion of macro 'GTEST_PATH_MAX_'
 9976 |   char cwd[GTEST_PATH_MAX_ + 1] = { '\0' };
      |            ^~~~~~~~~~~~~~~
```

Im using the gcc13 compiler from macports.

Considering the `gmock` I'm probably happy if I can turn off tests building.

**Comment by VictorEijkhout** [comment] 2024-01-21 15:15
Indeed, `-D FMT_TEST=OFF` prevented this error. More documentation of the cmake options would be nice? I only found this by reading the `CMakeLists.txt`.

**Comment by vitaut** [comment] 2024-01-21 15:16
The error comes from the bundled copy of gtest/gmock (https://github.com/google/googletest). Does building the latter work?

**Comment by VictorEijkhout** [comment] 2024-01-21 15:48
Googletest gives the same error.

**Comment by vitaut** [comment] 2024-01-21 16:03
Please report to https://github.com/google/googletest then.

**Comment by vitaut** [comment] 2024-01-23 16:28
Closing since this is not a bug in {fmt} but a PR with a patch to bundled gtest is welcome (but as commented above please also report to gtest).

**Closed by vitaut** 2024-01-23 16:28 UTC
