### ISSUE TITLE
clang 13 C++20 consteval error

### ISSUE THREAD

**Issue by englercj** [fmtlib/fmt#2455] opened 2021-08-15 15:51 UTC
I'm getting a compilation error with `8.0.1` using clang 13:

```
In file included from dependencies/fmtlib.fmt/fmt-8.0.1/src/format.cc:8:
dependencies/fmtlib.fmt/fmt-8.0.1/include/fmt/format-inl.h:92:54: error: call to consteval function 'fmt::basic_format_string<char>::basic_format_string<char [21], 0>' is not a constant expression
  if (written < count) FMT_THROW(system_error(errno, "cannot write to file"));
                                                     ^
dependencies/fmtlib.fmt/fmt-8.0.1/include/fmt/core.h:463:15: note: non-constexpr function 'strlen' cannot be used in a constant expression
      size_ = std::strlen(reinterpret_cast<const char*>(s));
              ^
dependencies/fmtlib.fmt/fmt-8.0.1/include/fmt/core.h:2835:51: note: in call to 'basic_string_view(&"cannot write to file"[0])'
  FMT_CONSTEVAL basic_format_string(const S& s) : str_(s) {
                                                  ^
dependencies/fmtlib.fmt/fmt-8.0.1/include/fmt/format-inl.h:92:54: note: in call to 'basic_format_string("cannot write to file")'
  if (written < count) FMT_THROW(system_error(errno, "cannot write to file"));
                                                     ^
```

Here is the full invocation:

```
clang++ -Idependencies/fmtlib.fmt/fmt-8.0.1/include -MMD -MP -m64 -Werror -ffast-math -O0 -g -mavx -Wall -Wextra -std=c++20 -fno-exceptions -fno-rtti -mcx16 -fvisibility=hidden -fvisibility-inlines-hidden -Wundef -o $(OBJDIR)/format.o -c dependencies/fmtlib.fmt/fmt-8.0.1/src/format.cc
```

And my full clang version if it helps:

```
$ clang --version
Debian clang version 13.0.0-++20210811062604+6789c4564a4b-1~exp1~20210811163414.34
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by vitaut** [comment] 2021-08-15 16:06
clang 13 hasn't been released yet. Do you mean the current development version of clang? Also do you have a godbolt repro?

**Comment by englercj** [comment] 2021-08-15 16:12
I'm using the Debian apt inghtly packages from llvm: https://apt.llvm.org/. I've also tried with 12 and get the same error. I haven't been able to get a reproduction in godbolt yet.

**Comment by englercj** [comment] 2021-08-15 16:32
Just downgraded and confirmed I'm seeing the same thing with clang 12:

```
$ make
==== Building fmt (debug_x64) ====
format.cc
In file included from dependencies/fmtlib.fmt/fmt-8.0.1/src/format.cc:8:
dependencies/fmtlib.fmt/fmt-8.0.1/include/fmt/format-inl.h:92:54: error: call to consteval function 'fmt::basic_format_string<char>::basic_format_string<char [21], 0>' is not a constant expression
  if (written < count) FMT_THROW(system_error(errno, "cannot write to file"));
                                                     ^
dependencies/fmtlib.fmt/fmt-8.0.1/include/fmt/core.h:463:15: note: non-constexpr function 'strlen' cannot be used in a constant expression
      size_ = std::strlen(reinterpret_cast<const char*>(s));
              ^
dependencies/fmtlib.fmt/fmt-8.0.1/include/fmt/core.h:2835:51: note: in call to 'basic_string_view(&"cannot write to file"[0])'
  FMT_CONSTEVAL basic_format_string(const S& s) : str_(s) {
                                                  ^
dependencies/fmtlib.fmt/fmt-8.0.1/include/fmt/format-inl.h:92:54: note: in call to 'basic_format_string("cannot write to file")'
  if (written < count) FMT_THROW(system_error(errno, "cannot write to file"));
                                                     ^
1 error generated.
make[1]: *** [fmt.make:180: obj/linux-debug_x64/fmt/format.o] Error 1
make: *** [Makefile:57: fmt] Error 2

$ clang --version
Debian clang version 12.0.1-++20210804103842+fed41342a82f-1~exp1~20210804084624.136
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by phprus** [comment] 2021-08-15 16:57
```libstdc++``` from Debian 9 does not support ```constexpr std::char_traits```.
```libstdc++``` from Debian 10 does not support ```is_constant_evaluated```.
https://distrowatch.com/table.php?distribution=debian and https://en.cppreference.com/w/cpp/compiler_support

```-std=c++20``` is not fully compatible with ```libstdc++``` 6.3.0, 8.3.0.

Please check code with ```libc++```.

**Comment by englercj** [comment] 2021-08-15 20:04
Upgrading libc++ did in-fact fix the issue, great catch there. Thanks for your help.

**Comment by ndevenish** [comment] 2021-09-09 11:22
I also ran into this, and solved by downgrading my `set(CMAKE_CXX_STANDARD 20)` to `set(CMAKE_CXX_STANDARD 17)` (wasn't otherwise using C++20 features).

**Comment by timblechmann** [comment] 2021-09-22 14:40
i'm seeing a slightly related error: appleclang (from xcode 12.5 and xcode 13) both ICE when compiling in c++20 mode. the ICE goes away when disabling the `FMT_CONSTEVAL` selection.

the code enables the consteval codepath when clang v11.1 is detected, though

**Comment by kotori2** [comment] 2021-09-24 17:27
> i'm seeing a slightly related error: appleclang (from xcode 12.5 and xcode 13) both ICE when compiling in c++20 mode. the ICE goes away when disabling the `FMT_CONSTEVAL` selection.
> 
> the code enables the consteval codepath when clang v11.1 is detected, though

@timblechmann 
Similar issue here. It seems this bug was introduced somewhere between `fmtlib` 70103 and 80001. 
I got the same `error: call to consteval function 'fmt::basic_format_string<char, char *&>::basic_format_string<std::basic_string_view<char>, 0>' is not a constant expression` error.
Currently using `Apple clang version 13.0.0 (clang-1300.0.29.3)` on macOS 12.0 beta.

**Comment by mwinterb** [comment] 2021-09-24 17:40
> > i'm seeing a slightly related error: appleclang (from xcode 12.5 and xcode 13) both ICE when compiling in c++20 mode. the ICE goes away when disabling the `FMT_CONSTEVAL` selection.
> > the code enables the consteval codepath when clang v11.1 is detected, though
> 
> @timblechmann
> Similar issue here. It seems this bug was introduced somewhere between `fmtlib` 70103 and 80001.
> I got the same `error: call to consteval function 'fmt::basic_format_string<char, char *&>::basic_format_string<std::basic_string_view<char>, 0>' is not a constant expression` error.
> Currently using `Apple clang version 13.0.0 (clang-1300.0.29.3)` on macOS 12.0 beta.

Your issue sounds more like #2438.

**Comment by kotori2** [comment] 2021-09-24 18:27
@mwinterb I just realized the error was followed by a compiler crash.
There is an example to reproduce: 
```
#include <fmt/format.h>

template<typename ... Args>
static void output_logs() {
    fmt::format("");
}

int main() {
    output_logs();
}
```
```
[ 50%] Building CXX object CMakeFiles/untitled.dir/main.cpp.o
clang: error: unable to execute command: Segmentation fault: 11
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Apple clang version 13.0.0 (clang-1300.0.29.3)
Target: x86_64-apple-darwin21.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /var/folders/cj/z4mkrrn51rlfcqvwq7_9pmfw0000gn/T/main-b1386c.cpp
clang: note: diagnostic msg: /var/folders/cj/z4mkrrn51rlfcqvwq7_9pmfw0000gn/T/main-b1386c.sh
clang: note: diagnostic msg: Crash backtrace is located in
clang: note: diagnostic msg: /Users/kotori0/Library/Logs/DiagnosticReports/clang_<YYYY-MM-DD-HHMMSS>_<hostname>.crash
clang: note: diagnostic msg: (choose the .crash file that corresponds to your crash)
clang: note: diagnostic msg: 

********************
make[3]: *** [CMakeFiles/untitled.dir/main.cpp.o] Error 254
make[2]: *** [CMakeFiles/untitled.dir/all] Error 2
make[1]: *** [CMakeFiles/untitled.dir/rule] Error 2
make: *** [untitled] Error 2
```

**Comment by vitaut** [comment] 2021-09-24 18:55
@kotori2, please open a new issue since it's unrelated to the current one.

**Comment by timblechmann** [comment] 2021-09-25 03:49
@kotori2's issue reduces to:
```
struct basic_format_string {
  template <typename S> consteval basic_format_string(S);
};
template <typename...> using format_string = basic_format_string;
auto format(format_string<>) -> int;
template <typename...> void output_logs() { format(""); }
int main() { output_logs(); }
```

**Comment by vitaut** [comment] 2021-09-25 13:42
`consteval` is disabled in Apple clang because of https://bugs.llvm.org/show_bug.cgi?id=51938.

**Comment by ndevenish** [comment] 2021-09-30 13:22
I'm also seeing this on linux, and now want to use some C++20 features. Is it worth adding a configuration check for (presumably) partially missing standard library support for this?

**Comment by vitaut** [comment] 2021-09-30 13:37
@ndevenish, there have been several unrelated issue reported here. What error do you get?

**Comment by vitaut** [comment] 2021-09-30 14:04
I think it's just a matter of refining the check here: https://github.com/fmtlib/fmt/blob/d141cdbeb0fb422a3fb7173b285fd38e0d1772dc/include/fmt/core.h#L461-L462

to account for unimplemented `is_constant_evaluated` in the standard library.

**Comment by phprus** [comment] 2021-09-30 14:19
@vitaut, Why is this if statement needed?

``std::char_traits<Char>::length(s)`` uses ``strlen`` if possible.

**Comment by ndevenish** [comment] 2021-09-30 14:25
It seems to specifically be using `std::strlen` in cases where it detects that the standard library is _not_ constant evaluated here. Is this a bug or I am misunderstanding the check?

https://github.com/fmtlib/fmt/blob/d141cdbeb0fb422a3fb7173b285fd38e0d1772dc/include/fmt/core.h#L352-L358

**Comment by vitaut** [comment] 2021-09-30 14:26
> Why is this if statement needed?

To get sensible code in debug mode: https://godbolt.org/z/56W3YG5xe.

**Comment by vitaut** [comment] 2021-09-30 14:28
> Is this a bug or I am misunderstanding the check?

It just doesn't play well with the fallback which is why it needs to be refined.

**Comment by vitaut** [comment] 2021-10-02 13:55
@ndevenish do you have a godbolt repro for the issue?

**Comment by vitaut** [comment] 2021-10-09 13:19
This should be fixed now.

**Closed by vitaut** 2021-10-09 13:19 UTC

**Comment by timblechmann** [comment] 2022-02-13 02:31
haven't been able to test, yet, but apparently fixed it in xcode13.3
