### ISSUE TITLE
Some locales have stopped working.

### ISSUE THREAD

**Issue by vomikan** [fmtlib/fmt#2748] opened 2022-02-08 21:38 UTC
In this sample first string is working fine.
![image](https://user-images.githubusercontent.com/6836805/153079681-9fc8f35e-2896-4c6c-8902-3ca12d8a3706.png)

But second one not
![image](https://user-images.githubusercontent.com/6836805/153079550-6dfdece5-65a3-48fd-a9c6-8de91ec06daf.png)

ba_RU, be_BY, bg_BG and others locales does not work as expected. They returns an empty string.
I've upgraded to 8.1.1

At the same tiem the following code is working. It seems to be a matter of the group separator.
![image](https://user-images.githubusercontent.com/6836805/153080723-4f52f905-a4e6-43ce-93c0-a00bc37b4f16.png)

**Comment by vitaut** [comment] 2022-02-09 15:30
I wasn't able to repro the issue. For example:

```c++
#include <iostream>
#include <locale>

#include "fmt/format.h"
int main() {
  auto s = fmt::format(std::locale("be_BY.UTF-8"), "{:L}", 1234567890);
  fmt::print("{}\n", s);
  std::cout.imbue(std::locale("be_BY.UTF-8"));
  std::cout << 1234567890;
}
```

prints

```
1 234 567 890
1 234 567 890
```

**Comment by vomikan** [comment] 2022-02-10 09:52
Could you please test de_DE and ba_RU locales as well ?

**Comment by vitaut** [comment] 2022-02-10 14:17
de_DE:

```
1234567890
1234567890
```

There is no ba_RU locale on my system but ru_RU gives:

```
1 234 567 890
1 234 567 890
```

Closing for now but feel free to reopen with more repro details.

**Comment by vomikan** [comment] 2022-02-10 14:17
I am using: 
• wxWidgets 3.1.4 (wxMSW 10.0) 
• Microsoft Visual Studio 17.0
• Microsoft Visual C++ 19.16.27045.0
• Windows SDK 10.0.19041.0
Running on:
• Windows 10 (build 19042), 64-bit edition
• Russian (UTF-8)

![image](https://user-images.githubusercontent.com/6836805/153425562-cc1f21ee-5e19-4a0a-b451-ac4f1049dad6.png)

**Closed by vitaut** 2022-02-10 14:17 UTC

**Comment by vitaut** [comment] 2022-02-10 15:45
`ru_RU.UTF-8` locale looks broken on your system: it gives -62 (0xc2) which is invalid UTF-8. I suggest reporting to Microsoft/STL. In the meantime you can workaround this by providing your own numpunct facet.

**Comment by vomikan** [comment] 2022-02-10 15:45
OK. Thank you.

**Comment by mwinterb** [comment] 2022-02-10 16:18
As more info for your report to Microsoft, it is likely that U+00A0 (NBSP) is the thousands separator for those locales, which after converting to UTF8 (0xC2 0xA0), doesn't fit into a single UTF8 code unit as required by numpunct.

**Comment by vomikan** [comment] 2022-02-10 19:24
@j0le sorry, it's my mistake.
Should be 1.234.567,89 INHO

**Comment by Atry** [comment] 2022-02-10 21:19
Since the type of `numpunct::thousands_sep` is `char`, it is impossible to support UTF-8 encoding, where the separator might be a multibyte code point.

**Comment by vomikan** [comment] 2022-02-11 14:34
> Since the type of `numpunct::thousands_sep` is `char`, it is impossible to support UTF-8 encoding, where the separator might be a multibyte code point.

Possibly, if it was an unsigned char, then the value \xa0 would not cause an error.

I'm forced to use a workaround:
```
        auto test = fmt::format(std::locale(locale.c_str()), "{:.2Lf}", 1234567.89);
        for (auto &i : test) { if (i < 0) i = ' ';}   
``` 
It's working fine.
        But I can't use non-breaking space
```    for (auto &i : test) { if (i < 0) i = '\xa0';}   ``` as result the test variable became invalid.

**Comment by StephanTLavavej** [comment] 2022-02-11 23:21
I believe this is [DevCom-1598113](https://developercommunity.visualstudio.com/t/1598113) "`std::locale("FR-fr")` produces incorrect thousands separator for `wchar_t` specialization on Windows 11". I was able to reduce that to a UCRT test case, ruling out [microsoft/STL](https://github.com/microsoft/STL) as the root cause:

```
C:\Temp>type meow.cpp
```
```cpp
#include <locale.h>
#include <stdio.h>

int main() {
    const char* const loc = "FR-fr";
    setlocale(LC_ALL, loc);
    const unsigned int val = static_cast<unsigned int>(localeconv()->_W_thousands_sep[0]);
    printf("_W_thousands_sep for %s is %u.\n", loc, val);
}
```
```
C:\Temp>cl /EHsc /nologo /W4 meow.cpp && meow
meow.cpp
_W_thousands_sep for FR-fr is 8239.
```

I've reported this to the UCRT maintainers.

**Comment by pdimov** [comment] 2022-02-12 03:33
Doesn't look like the above issue. The separator is 160, not 8239. But since 160 is 0xC2 0xA0 in UTF-8 encoding, and since the separator is a single `char`, it returns 0xC2 there. (As already mentioned upthread.)
