### ISSUE TITLE
Transmission and fmt 10.0.0

### ISSUE THREAD

**Issue by GaryElshaw** [fmtlib/fmt#3497] opened 2023-06-19 03:35 UTC
Kia ora, [Transmission](https://github.com/transmission/transmission) just updated fmt to 10.0.0 and there are an immense amount of warnings during compilation. Is there something i can do to help with this for both projects?

The below is some of the compilation warnings on Manjaro Linux 6.2.16-2-MANJARO with X11, cmake 3.26.4, and Gnome 44.1.

[fmt.txt](https://github.com/fmtlib/fmt/files/11783804/fmt.txt)

**Comment by vitaut** [comment] 2023-06-19 05:24
At least some of the warnings look the same as the ones reported in #3354. They are caused by a gcc bug but worked around in {fmt} master. If you are referring to some other warning please post it here.

**Comment by vitaut** [comment] 2023-06-20 12:23
Closing per comment above.

**Closed by vitaut** 2023-06-20 12:23 UTC

**Comment by GaryElshaw** [comment] 2023-08-05 05:22
Just a note that i think the warnings might be related to CMake. They only appear when CMake is building with debug information, no warnings when building release.
