### ISSUE TITLE
Is `CustomValue::format` only for internal use?

### ISSUE THREAD

**Issue by jamboree** [fmtlib/fmt#341] opened 2016-06-08 08:55 UTC
It's assigned within `MakeValue<Formatter>`:
```c++
  template <typename T>
  MakeValue(const T &value,
            typename EnableIf<Not<
              ConvertToInt<T>::value>::value, int>::type = 0) {
    custom.value = &value;
    custom.format = &format_custom_arg<T>;
  }
```

and `format_custom_arg` is defined as:
```c++
  // Formats an argument of a custom type, such as a user-defined class.
  template <typename T>
  static void format_custom_arg(
      void *formatter, const void *arg, void *format_str_ptr) {
    format(*static_cast<Formatter*>(formatter),
           *static_cast<const Char**>(format_str_ptr),
           *static_cast<const T*>(arg));
  }
```
where `format` is found by ADL, this seems like a customization point to me.

However, in `FMT_VARIADIC_`, it's called this way:
```
ArgArray::template make<fmt::BasicFormatter<Char> >(args)...
```

That means, it assumes `BasicFormatter` always uses `ArgFormatter<CharType>`, that is, even you could supply your `CustomArgFormatter` as described [here](http://fmtlib.net/latest/api.html#argument-formatters), there's no way for the CustomValue to use the `CustomArgFormatter` that you supplied. (unless you avoid the FMT_VARIADIC_ hack and specify the Formatter manually)

Besides, the format-ADL mechanism allows you to do custom parsing on the format string, but does anyone really need it?

If `CustomValue::format` is designed for extension (w/o custom parsing), I think there could be a better way. For example, a customization point that takes `FormatSpec`, the real UDT, and the writer.

Why do I care at all? Recently I try to implement a pre-parsed format object, which parses the format string into its internal data structure. And `CustomValue::format` is a big headache for that. It seems that the current CustomValue::format is tightly coupled with some internal details.

**Comment by vitaut** [comment] 2016-06-08 14:03
Good question. As you've already found out `FMT_VARIADIC` uses `fmt::BasicFormatter` and there is no way to pass a custom formatter to it. Therefore you'll need to provide your own version of this macro (or use C++11) if you want to use a custom argument formatter with user-defined types.

> If CustomValue::format is designed for extension (w/o custom parsing), I think there could be a better way. For example, a customization point that takes FormatSpec, the real UDT, and the writer.

`CustomValue::format` is designed for extension with custom parsing, for example, [Date and time formatting](http://fmtlib.net/latest/api.html#date-and-time-formatting), so passing `FormatSpec` won't work. However, `FMT_VARIADIC_` can be changed to accept a formatter type to make defining a custom `FMT_VARIADIC` easier. What do you think?

**Comment by jamboree** [comment] 2016-06-08 14:31
Another possible way to support custom parsing might be: if we encounter an unrocognized character, then skip to `}` and store the StringRef between `:` and `}` into `FormatSpec`, or probably we can demand a sentinel character for custom format, e.g. `%`. What do you think?

**Comment by vitaut** [comment] 2016-06-08 14:44
I think it's possible to pass a portion of a format string via `FormatSpec`, but I don't see any benefit in doing so compared to just passing a string reference. Most of the fields in `FormatSpec` will be irrelevant anyway. Also passing `FormatSpec` won't change the fact that you'll need to define a custom version of `FMT_VARIADIC`.

**Comment by jamboree** [comment] 2016-06-08 15:25
What I really care is whether the custom arg should affect the format parsing, as it currently does.

Though I talked about the FMT_VARIADIC&ArgFormatter issue, I don't really need to customize ArgFormatter myself, it's just my observation of the API incapability. (I know my thinking here is non-linear).

Think about how we customize UDT output with `std::iostream`:
```c++
template<class Char, class T>
std::basic_ostream<Char>& operator<<(std::basic_ostream<Char>&, const T&);
```

I imagine the format counterpart would be:
```c++
template<class Char, class T>
void do_format(BasicWriter<Char> &,  const FormatSpec &, const T &);
```

I'm not sure I need BasicFormatter or any CustomArgFormatter here.

**Comment by vitaut** [comment] 2016-06-08 15:36
Unfortunately passing just `BasicWriter` won't work because `do_format` might need access to other arguments and `BasicWriter` doesn't know anything about them. So one has to pass a formatter there. If you don't care about custom argument formatting, the extension point becomes:

```c++
template<class Char, class T>
void format(BasicFormatter<Char> &,  const Char *&, const T &);
```
which is similar to your `do_format` and is already supported.

**Comment by jamboree** [comment] 2016-06-08 16:02
This is actually what the extension point currently is. If the user wants to use the extension point, he might want to access the `FormatSpec` (which is far simpler) instead of doing the parsing himself. As it currently designed, the parsing is required at the user side, I think that's why you need a `BasicFormatter` here to help the parsing. The current design for customization is arg driven, so you can't make a `FormatSpec` beforehand. In the reverse design like I talked above, the customization is format-str driven, so you can make a `FormatSpec` if the format-str confirms to the syntax or pass the raw format-str otherwise. I think this way might be more user-friendly since you're not always need custom parsing.

**Comment by jamboree** [comment] 2016-06-08 16:12
FWIW, what I'm trying to do is:

```c++
fmt::Format f("ab{}d"); // pre-parsed format
fmt::print(f, 'c');
```

In doing this, it's impossible to have arg driven custom parsing. So an alternate design is required.
I'm not sure if you'd be interested though.

**Comment by vitaut** [comment] 2016-06-09 15:17
> If the user wants to use the extension point, he might want to access the FormatSpec (which is far simpler) instead of doing the parsing himself.

The problem is that `FormatSpec` is not extensible. For example, it won't be possible to implement time and date formatting without additional parsing. If the user wants `FormatSpec`, it is possible to provide an API to easily get one by parsing the format string at the current position. But I think it is important to have the ability to implement parsing on the user side.

Thanks for the use case, it is quite helpful. Why are you interested in pre-parsing, is it for performance reasons?

Custom arguments is not the only problem here. `BasicFormatter` by design uses argument type information (and even values) during parsing. For example in

```c++
fmt::print("{:.{}}", 4.2, 3);
```
to get precision and put it in `FormatSpec`, formatter needs access to the second argument. Also for type checking it needs to know that the first argument has a floating-point type. So you won't be able to reuse `BasicFormatter` or `FormatSpec` in pre-parsing.

**Comment by jamboree** [comment] 2016-06-09 16:43
The intent is indeed for performance, in case that the same format will be output many times so it might be beneficial to save the parsing every time.
Dynamic precision/width is not really a problem, it's already implemented in my experiment. What's missing is custom parsing which can be solved with a extended `FormatSpec` that stores the raw string.

**Comment by vitaut** [comment] 2016-06-10 00:45
One option is to store `FormatSpec` objects for built-in types and portions of format strings for other types during pre-parsing, and use these during the actual formatting. I don't think there is a need to store the format string in `FormatSpec` itself because they are mutually exclusive. It's better to have something like a discriminated union:

```c++
struct {
  enum Type { BUILTIN, CUSTOM } type;
  union {
    FormatSpec spec;
    const char *str;
  };
};
```
What do you think?

BTW I'd recommend doing some benchmarking to make sure that parsing actually needs to be optimized in your usage scenario. Last time I checked the parsing overhead was small compared even to string construction, not to mention I/O.

**Comment by jamboree** [comment] 2016-06-10 06:22
Yeah I've thought of using a union as well, but why I want to have it in `FormatSpec` itself is that the `flags_` can be use as the discriminator. Another way is to pass the raw-str as an additional param to the extension point.

In addition to possible performance benefit, another nice thing to have a pre-parsed format is that you can validate the format before you use it (think about `std::regex`).

When it comes to validation, I'm thinking if it'd be better to allow the args to ignore the inapplicable format-spec instead of throwing. Or at least provide an option for that (permissive-mode?).

**Comment by jamboree** [comment] 2016-06-10 07:56
In my simple test the pre-parsed one saves about 20% of the time.

```c++
namespace fmt {
    void pre_parsed(const BasicFormat<char> &f, ArgList args) {
        BasicMemoryWriter<char> writer;
        BasicFormatVisitor<char> op = {writer};
        f.apply(op, args);
    }

    void on_the_fly(CStringRef format_str, ArgList args) {
        MemoryWriter w;
        w.write(format_str, args);
    }

    FMT_VARIADIC(void, pre_parsed, const BasicFormat<char> &)
    FMT_VARIADIC(void, on_the_fly, CStringRef)
}

int main()
{
    int round = 100000;
    char const fstr[] =
        "abc!@^&*{0:{1}}def()_+{2:<4x}ghi1234{3:=+4}jkl5678{4:.2f}"
        "mno90`~,.[]{5:3.{6}f}pqr:<>/?{7:+010.4g}stu#$%{{{8:{9}}}}vwxyz"
        "{10:0.10f}:{11:04}:{12:+g}:{13}:{14}:{15}:%"
        ;
    {
        auto start = std::chrono::high_resolution_clock::now();
        for (int i = 0; i != round; ++i)
            fmt::on_the_fly(fstr, 4.2, 10, 0x42, 42, 1.2345, 6.789, 2, 392.65, -2, 2, 1.234, 42, 3.13, "str", reinterpret_cast<void*>(1000), 'X');
        auto stop = std::chrono::high_resolution_clock::now();
        auto elapsed = std::chrono::duration_cast<std::chrono::microseconds>(stop - start);
        std::cout << "us: " << elapsed.count() << "\n";
    }
    fmt::BasicFormat<char> f(fstr);
    {
        auto start = std::chrono::high_resolution_clock::now();
        for (int i = 0; i != round; ++i)
            fmt::pre_parsed(f, 4.2, 10, 0x42, 42, 1.2345, 6.789, 2, 392.65, -2, 2, 1.234, 42, 3.13, "str", reinterpret_cast<void*>(1000), 'X');
        auto stop = std::chrono::high_resolution_clock::now();
        auto elapsed = std::chrono::duration_cast<std::chrono::microseconds>(stop - start);
        std::cout << "us: " << elapsed.count() << "\n";
    }
    return 0;
}
```

**Comment by vitaut** [comment] 2016-06-10 13:54
> Yeah I've thought of using a union as well, but why I want to have it in FormatSpec itself is that the flags_ can be use as the discriminator.

You can do this and I can add a constant `FLAG_CUSTOM` or similar to mark where standard flags end if you like. However, the union will be more compact and better reflect the semantics (because passing both a format string and `FormatSpec` is redundant).

> In my simple test the pre-parsed one saves about 20% of the time.

Cool.

Anyway, I do think that parsing should be done on the user-side for custom types, but I am open to the changes that can simplify your pre-parsed approach without affecting existing functionality.

**Comment by vitaut** [comment] 2016-06-14 13:29
Closing this for now, but feel free to reopen if you have any specific suggestions.

**Closed by vitaut** 2016-06-14 13:29 UTC
