### ISSUE TITLE
consteval error with FreeBSD 13.1 and Clang13

### ISSUE THREAD

**Issue by phire** [fmtlib/fmt#3032] opened 2022-08-10 07:28 UTC
```
/usr/home/buildbot/freebsd/pr-freebsd-x64/build/Source/UnitTests/Common/BitFieldTest.cpp:234:27: error: call to consteval function 'fmt::basic_format_string<char, BitField<0, 64, unsigned long, unsigned long> &>::basic_format_string<char [7], 0>' is not a constant expression
    EXPECT_EQ(fmt::format("{:02x}", object.full_u64),
                          ^
/usr/home/buildbot/freebsd/pr-freebsd-x64/build/Source/UnitTests/Common/BitFieldTest.cpp:234:27: note: undefined constructor 'basic_format_string<char [7], 0>' cannot be used in a constant expression
/usr/home/buildbot/freebsd/pr-freebsd-x64/build/Externals/fmt/include/fmt/core.h:3115:28: note: declared here
  FMT_CONSTEVAL FMT_INLINE basic_format_string(const S& s) : str_(s) {
                           ^
/usr/home/buildbot/freebsd/pr-freebsd-x64/build/Source/UnitTests/Common/BitFieldTest.cpp:236:27: error: call to consteval function 'fmt::basic_format_string<char, BitField<0, 64, long, long> &>::basic_format_string<char [7], 0>' is not a constant expression
    EXPECT_EQ(fmt::format("{:02x}", object.full_s64),
```

I could try and make a minimal reproduction and/or test on master, but I don't have a freebsd system setup, and this is just #2455 again. If you need one, just ask.

Looks like last time you worked around this issue by [disabling consteval for all AppleClang](https://github.com/fmtlib/fmt/blob/master/include/fmt/core.h#L265). But it seems the bug isn't in AppleClang, just when you have both Regular Clang and libc++. And now we have a second OS with libc++ plus a new enough version of Clang. 

Our testing showed that upgrading to Clang14 fixed the issue. Also forcing `FMT_CONSTEVAL` off on FreeBSD + Clang13 fixed it https://github.com/dolphin-emu/dolphin/pull/10973, which is the solution we will go with. 

But maybe you should update master to check for `_LIBCPP_VERSION` instead of `__apple_build_version__`. Also, since this seems to be fixed in later versions of Clang, maybe you should limit that check to just Clang 13?

**Comment by mpiatka** [comment] 2022-08-10 10:43
I run into the same or similar issue on both GCC and clang on c++20. Reproduces on current master. Minimal reproduction:
```C++
#include <string_view>
#include <fmt/core.h>

extern int get_number();

template<typename... Args>
inline void log_msg(std::string_view msg, Args... args){
    fmt::print(msg, args...);
}

int main(){
    log_msg("{}\n", get_number());

    return 0;
}
```
[compiler explorer link](https://godbolt.org/z/6PsEEPd36)

**Comment by vitaut** [comment] 2022-08-10 16:44
@mpiatka, the error in your example is unrelated and expected because the format string should be known at compile time: https://fmt.dev/latest/api.html#core-api.

**Comment by vitaut** [comment] 2022-08-10 16:45
@phire, could you provide a repro (ideally on godbolt)?

**Comment by phire** [comment] 2022-08-10 21:11
Godbolt doesn't seem to have freebsd, but I'll download a VM and get you a repro.

**Comment by vitaut** [comment] 2022-08-21 13:41
> But maybe you should update master to check for _LIBCPP_VERSION instead of __apple_build_version__.

I don't think it's a good idea because this config works on some systems, e.g. https://godbolt.org/z/rMcYPj66P.

**Comment by vitaut** [comment] 2022-08-21 14:02
I wasn't able to repro the issue on the following test case:

test.cc:
```c++
#include <fmt/core.h>

int main() {
  uint64_t full_u64;
  auto s = fmt::format("{:02x}", full_u64);
}
```

```
% uname -a
FreeBSD freebsd 13.1-RELEASE-p1 FreeBSD 13.1-RELEASE-p1 GENERIC amd64
% clang++ --version
FreeBSD clang version 13.0.0 (git@github.com:llvm/llvm-project.git llvmorg-13.0.0-0-gd7b669b3a303)
Target: x86_64-unknown-freebsd13.1
Thread model: posix
InstalledDir: /usr/bin
```

Please provide a self-contained repro.

**Comment by vitaut** [comment] 2022-10-01 16:32
Closing as I wasn't able to reproduce the issue in the described configuration. Feel free to reopen with more repro details.

**Closed by vitaut** 2022-10-01 16:32 UTC
