### ISSUE TITLE
[BUG] Unable to print colorized text to the console

### ISSUE THREAD

**Issue by codeszsoft** [fmtlib/fmt#2682] opened 2021-12-29 09:14 UTC
I'm trying to print a colorized text to the console with fmt library. And this is my code

```
#include <fmt/core.h>
#include <fmt/color.h>

int main(int argc, char **argv)
{
	fmt::print(fmt::fg(fmt::color::blue), "The text is BLUE!");
	
	return 0;
}
```

but the result is
```
[38;2;000;000;255mThe text is BLUE![0m
```

**Comment by Joker2387089590** [comment] 2021-12-29 15:04
You may need a modern terminal to run your program, try zsh on Linux or Windows Terminal on Windows.

**Comment by vitaut** [comment] 2021-12-29 15:15
Duplicate of #1794.

**Closed by vitaut** 2021-12-29 15:15 UTC
