### ISSUE TITLE
formatting chrono with precision

### ISSUE THREAD

**Issue by brevzin** [fmtlib/fmt#3219] opened 2022-12-08 15:30 UTC
```cpp
#include <chrono>
#include <fmt/chrono.h>

int main() {
    using namespace std::chrono;

    // this one prints 1.00s, as expected
    fmt::print("{:.2}\n", duration<double>(1.0));

    // this one prints 1s but shouldn't compile
    fmt::print("{:.2}\n", duration<int>(1));

    // these both print .2
    fmt::print("{:.2}\n", time_point<system_clock, duration<double>>(duration<double>(1.0)));
    fmt::print("{:.2}\n", time_point<system_clock, duration<int>>(duration<int>(1)));
}
```

If we look at the standard spec, it's clear that using _precision_ with a `duration` is only valid for floating point (https://eel.is/c++draft/time.format#1.sentence-4), so the second call there should be rejected. 

There's some ambiguity in the standard spec right now about what formatting a `time_point<system_clock, duration<int>>` with `{:.2}` actually means (valid or not? probably not?) but either way, printing `.2` in either case is definitely incorrect.

**Comment by vitaut** [comment] 2022-12-09 22:42
Good catch(es), thanks. As usual, PRs are welcome =).

**Comment by phprus** [comment] 2022-12-10 09:18
Why is printing ``.2`` incorrect?
I think, in ``chrono-specs``, the string ``.2` is a valid ``literal-char``.

**Comment by jwakely** [comment] 2022-12-10 10:39
No, the first character of a chrono-spec must be `%`

**Comment by jwakely** [comment] 2022-12-10 10:41
If you want to write literal characters before the first % put them before the replacement field: `".2{}\n"`

**Comment by vitaut** [comment] 2022-12-21 22:45
The time point issue is fixed in #3232 (thanks @ShawnZhong) but precision of durations with integral representation is useful and will continue to be supported.

**Closed by vitaut** 2022-12-21 22:45 UTC
Labels: help wanted

**Comment by ShawnZhong** [comment] 2022-12-24 00:20
Thanks for clarifying. I'm good with precision for integral durations. 

I have some follow-up comments/questions (which I can open a new issue if needed): 

- I agree that precision with `%S` is useful and should continue to be supported:
  ```cpp
  // %S writes the second as a decimal number
  fmt::print("{:.8%S}\n", 1234ns); // prints 00.000001234
  ```

- I'm not sure what should be the expected behavior of just specifying the precision:
   ```cpp
   fmt::print("{:.8}\n", 1234ns); // prints 1234ns
   ```

- Precision with `%Q` throws `format_error`, which is reasonable
   ```cpp
   // %Q writes the count of ticks of the duration
   fmt::print("{:.8%Q}", 1234ns); // precision not allowed for this argument type
   ```

- Whether or not `%M` and `%H` are valid for formatting durations? 

    ```cpp
    // %M writes the minute as a decimal number.
    fmt::print("{:.8%M}\n", 123.4min); // prints 03
    // %H writes the hour (24-hour clock) as a decimal number. 
    fmt::print("{:.8%H}\n", 12.34h);   // prints 12
    ```

**Comment by vitaut** [comment] 2022-12-26 22:02
> I'm not sure what should be the expected behavior of just specifying the precision

This seems pretty harmless and we can continue ignoring precision here (maybe even ignore in other cases).

> Whether or not %M and %H are valid for formatting durations?

I think `%M` and `%H` make sense for time points but not necessarily for durations. The same probably applies to `%S`, not sure why we allowed them in the first place. Unless, of course, they are supported by the standard and the date library in which case we should check with Howard about the rationale.

**Comment by jwakely** [comment] 2023-01-12 15:27
The standard seems clear:

> However, if a flag refers to a “time of day” (e.g. %H, %I, %p, etc.), then a specialization of `duration` is
interpreted as the time of day elapsed since midnight.

So %H uses the value of `chrono::floor<chrono::hours>(dur).count()` and %M uses the value of `chrono::floor<chrono::minutes>(dur).count()`.

**Comment by jwakely** [comment] 2023-01-12 15:34
Also see the example in [time.format] p4.
