### ISSUE TITLE
cannot open file : No such file or directory 

### ISSUE THREAD

**Issue by illegal-instruction-co** [fmtlib/fmt#3368] opened 2023-03-29 16:59 UTC
```cpp
inline void WriteLogToFile(const fmt::string_view log) {
	std::scoped_lock<std::mutex> lock(m_mtx);
	auto out = fmt::output_file("./Log.log", fmt::file::WRONLY | fmt::file::CREATE | fmt::file::APPEND);
	out.print("{} \n", log);
}
```

This code works as expected under Windows without exception. If the log file doesnt exists, it is creating new one. But under Ubuntu 22.04 ( gcc 12.2 ), it is throwing an exception as following:

cannot open file : No such file or directory 

Note: binary has sudo permission.

**Comment by sunmy2019** [comment] 2023-03-30 11:43
cannot reproduce on my ubuntu 22.04 gcc 12.1.0 with the following piece of code
 cannot reproduce on godbolt either: https://godbolt.org/z/hWEfrs97c

```cpp
#include <fmt/format.h>
#include <fmt/os.h>
#include <mutex>

std::mutex m_mtx;

inline void WriteLogToFile(const fmt::string_view log) {
	std::scoped_lock<std::mutex> lock(m_mtx);
	auto out = fmt::output_file("./Log.log", fmt::file::WRONLY | fmt::file::CREATE | fmt::file::APPEND);
	out.print("{} \n", log);
}

int main (){
    WriteLogToFile("123");
}
```

**Comment by sunmy2019** [comment] 2023-03-30 13:25
can you provide a minimal reproducing example?

**Comment by sunmy2019** [comment] 2023-03-30 14:15
Exactly. And when i run it twice, I got "123 \n123 \n" in my file

**Comment by sunmy2019** [comment] 2023-03-30 14:17
How about testing opening/writing files with the native os handle?

**Comment by mwinterb** [comment] 2023-04-03 20:06
If possible, an strace log may also be helpful.

**Comment by illegal-instruction-co** [comment] 2023-04-04 11:56
> If possible, an strace log may also be helpful.

Im not sure how do i it. But i guess i can create a simple sample env.

**Comment by ilyapopov** [comment] 2023-04-12 09:25
Prepend your executable with `strace` when running:

    strace ./my-executable

It will show the log of all the syscalls the executable makes, where you'll be able to see what exact syscall that causes the error and its arguments. This will allow identifying what exactly went wrong.

**Comment by vitaut** [comment] 2023-04-13 15:41
`output_file` forwards the flags to `open`

https://github.com/fmtlib/fmt/blob/75f3b1c09485986427b8a46272f6b9570366e1aa/src/os.cc#L232

so check that they are correct and you have permissions to create the file.

Closing as this doesn't look like an issue with {fmt}.

**Closed by vitaut** 2023-04-13 15:41 UTC
