### ISSUE TITLE
CMAKE_CXX_STANDARD 11 is incorrect when using windows clang gnu frontend

### ISSUE THREAD

**Issue by DaanDeMeyer** [fmtlib/fmt#1237] opened 2019-07-18 19:55 UTC
CMake 3.15 just released with support for Clang's GNU frontend on Windows (clang with gnu like options instead of clang-cl). When using Clang with the GNU frontend as CMake's compiler, fmt fails to compile because it specifies the C++ version as C++11 while the MSVC standard library headers are already written using C++14.

To solve this issue, we could set `CMAKE_CXX_STANDARD` to C++14 when we detect that Clang's GNU frontend is used on Windows. Is this an acceptable solution?

**Comment by DaanDeMeyer** [comment] 2019-07-18 20:05
After setting the C++ version to C++14, compilation fails with the following error from gtest:

```
C:\Users\daan\scoop\shims\clang++.exe  -DFMT_LOCALE -DFMT_USE_FILE_DESCRIPTORS=1 -DFMT_USE_GRISU=1 -DGTEST_HAS_STD_WSTRING=1 -DGTEST_USE_OWN_TR1_TUPLE=1 -D_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING=1 -I../include -isystem ../test/gtest -isystem ../test/gmock -isystem ../test/. -g -Xclang -gcodeview -O0 -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd   -fno-delete-null-pointer-checks -std=gnu++14 -MD -MT test/CMakeFiles/grisu-test.dir/grisu-test.cc.obj -MF test\CMakeFiles\grisu-test.dir\grisu-test.cc.obj.d -o test/CMakeFiles/grisu-test.dir/grisu-test.cc.obj -c ../test/grisu-test.cc
In file included from ../test/grisu-test.cc:9:
../test/gtest\gtest.h:1371:27: error: declaration conflicts with target of using declaration already in scope
template <typename Tuple> struct tuple_size;
                          ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.21.27702\include\utility:339:8: note: target of using declaration
struct tuple_size;
       ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.21.27702\include\utility:566:16: note: using declaration
    using _STD tuple_size;
               ^
In file included from ../test/grisu-test.cc:9:
../test/gtest\gtest.h:1374:8: error: explicit specialization of non-template struct 'tuple_size'
struct tuple_size<GTEST_0_TUPLE_(T) > {
       ^         ~~~~~~~~~~~~~~~~~~~~
../test/gtest\gtest.h:1379:8: error: explicit specialization of non-template struct 'tuple_size'
struct tuple_size<GTEST_1_TUPLE_(T) > {
       ^         ~~~~~~~~~~~~~~~~~~~~
../test/gtest\gtest.h:1384:8: error: explicit specialization of non-template struct 'tuple_size'
struct tuple_size<GTEST_2_TUPLE_(T) > {
       ^         ~~~~~~~~~~~~~~~~~~~~
../test/gtest\gtest.h:1389:8: error: explicit specialization of non-template struct 'tuple_size'
struct tuple_size<GTEST_3_TUPLE_(T) > {
       ^         ~~~~~~~~~~~~~~~~~~~~
../test/gtest\gtest.h:1394:8: error: explicit specialization of non-template struct 'tuple_size'
struct tuple_size<GTEST_4_TUPLE_(T) > {
```

This should be fixed in the master branch of gtest but is not yet released.

**Comment by vitaut** [comment] 2019-07-19 05:12
> Is this an acceptable solution?

Sure, a PR is welcome.

> This should be fixed in the master branch of gtest but is not yet released.

A bundled version of gtest could be patched.

**Comment by DaanDeMeyer** [comment] 2019-07-19 08:48
I tried patching built-in gtest but it spews out too many warnings I'm not willing to fix. Updating to the latest gtest commit might fix the issues but I did not immediately find a way to get a header only version of gtest like the one used in fmt.

**Comment by risa2000** [comment] 2019-07-22 12:43
I was hit by this error today and I can confirm that updating `googletest` to the latest branch solved the issue.

Incidentally, when looking into the error, I was checking if I am not compiling with the "wrong" standard, but did not find any to be forced in the lib.

**Comment by vitaut** [comment] 2019-07-26 09:22
Closing per https://github.com/fmtlib/fmt/pull/1238#issuecomment-514518770 since it should be addressed by CMake itself. In the meantime it's possible to override `CMAKE_CXX_STANDARD` as a workaround.

**Closed by vitaut** 2019-07-26 09:22 UTC
