### ISSUE TITLE
detail::is_back_insert_iterator lacks a specialisation for fmt::appender

### ISSUE THREAD

**Issue by jagoly** [fmtlib/fmt#3776] opened 2023-12-28 04:00 UTC
As title, I believe this is an oversight. This results in extra code being generated for anything using memory_buffer or iterator_buffer. Of course fmt is a bit complicated so there could well be a reason for this :)

Also related, is there a reason that basic_format_context::advance_to is not constexpr? Is it for compatibility with std::format? I've got a few types I'd like to make constexpr-formattable, but the ones that use advance_to fail to compile.

**Comment by vitaut** [comment] 2023-12-28 04:49
Could you show the godbolt example with the extra generated code?

`advance_to` is not `constexpr` simply because there was no need to make it constexpr yet. Again, could you show an example where `constexpr` would be beneficial?

**Comment by jagoly** [comment] 2023-12-28 08:09
sure, here's what I've been hacking on, simplified to remove most of the stuff not needed for this example https://godbolt.org/z/691xEs1fd

Change line 81 to 1 and you can see that neither gcc or clang is able to optimise away the calls to advance_to, resulting in a few extra instructions. Admittedly, not many given all the other code generated, but they are there.

As for where constexpr could be beneficial, it's for the same reason that having the builtin types be constexpr formattable is nice. In my case, the only types I've actually needed to format at compile time are ints and my custom StackString type (which doesn't need advance_to), but I'm sure there are other use cases for formatting complex user types at compile time. Especially given that everything else already works, the only thing needed to make the type in the example formattable at compile time is marking advance_to as constexpr (which I've tested locally).

**Comment by vitaut** [comment] 2023-12-30 04:43
Thanks for the repro, I see what the problem is now. Here's a simpler one for future reference: https://godbolt.org/z/zfqh6hvrr. PRs to make both changes would be welcome.

**Comment by vitaut** [comment] 2024-01-09 03:39
Closing since `advance_to` has been already optimized but a PR to add constexpr is welcome.

**Closed by vitaut** 2024-01-09 03:39 UTC
Labels: enhancement
