### ISSUE TITLE
Can't print map<string, any>

### ISSUE THREAD

**Issue by FisherDock** [fmtlib/fmt#2590] opened 2021-11-06 00:05 UTC
Hi, 

I tried to print `map<string, any>` using `{fmt}`, but compiler(Clang12, C++17) says

` In template: cannot pass object of non-trivial type 'std::map<std::basic_string<char>, std::any>' through variadic method; call will abort at runtime`.

Is there a way to print the map container?  I also want to convert the map to a JSON string. 

Thank you.

**Comment by vitaut** [comment] 2021-11-06 13:30
Duplicate of #2589.

**Closed by vitaut** 2021-11-06 13:30 UTC
