### ISSUE TITLE
Integral constant overflow

### ISSUE THREAD

**Issue by albert-github** [fmtlib/fmt#3274] opened 2023-01-15 13:57 UTC
https://github.com/fmtlib/fmt/blob/0f42c17d85f26bbbd6a30d71ce8306d371426bfc/include/fmt/format-inl.h#L1146-L1147

In the spdlog project (see issue https://github.com/gabime/spdlog/issues/2607) I got the warning messages:
```
...\deps\spdlog\include\spdlog\fmt\bundled\format-inl.h(1154): warning C4307: '*': integral constant overflow
...\deps\spdlog\include\spdlog\fmt\bundled\format-inl.h(1186): warning C4307: '*': integral constant overflow
...\deps\spdlog\include\spdlog\fmt\bundled\format-inl.h(1207): warning C4307: '*': integral constant overflow
```
and I was referred to this project.
Line numbers are a little bit different (probably a slightly other version)

**Comment by jk-jeon** [comment] 2023-01-16 23:30
I think this is a duplicate of this: https://github.com/fmtlib/fmt/issues/3163

**Comment by albert-github** [comment] 2023-01-17 08:46
It is a duplicate, but it is quite annoying, so it would be good when in fmtlib the code was modified (e.g. a cast) so that the warning disappears.

**Comment by vitaut** [comment] 2023-01-25 04:55
This is an MSVC bug which is worked around in https://github.com/fmtlib/fmt/commit/a2c05a10ec875712bfee739a05ed99fc3915f4e9.

**Closed by vitaut** 2023-01-25 04:55 UTC
