### ISSUE TITLE
Need a global variable to turn off/on emiting of ANSI codes

### ISSUE THREAD

**Issue by kvtb** [fmtlib/fmt#2520] opened 2021-09-29 12:53 UTC
Need a global variable to turn off/on emitting of ANSI codes.

When `stdout` is not a `tty`, emiting of ANSI codes must be off.

For example when a program run like `./progname | grep something` or `./progname | less`.

Detecting of TTY state might be off scope of `fmt` library, but in `fmt` there should be a global variable a library user could set to `false` suppressing emitting of ANSI codes

**Comment by kvtb** [comment] 2021-09-29 14:44
> Maybe an environment variable [NO_COLOR](https://no-color.org/) as well?

I'd left that logic up to the user code.

There could be too many inputs to bring them into the library :
 * `isatty(STDOUT_FILENO)`
 * `getEnv("TERM", "dumb") != "dumb"`
 * `!isWindows`
 * command line switches `--color`, `--no-color`
 * `getEnv("NO_COLOR")`, `getEnv("COLOR")`
 * ...

**Comment by vitaut** [comment] 2021-09-29 14:57
Duplicate of #2137.

**Closed by vitaut** 2021-09-29 14:57 UTC
Labels: duplicate
