### ISSUE TITLE
char8_t formatting converts to integers

### ISSUE THREAD

**Issue by cjdb** [fmtlib/fmt#1188] opened 2019-06-01 19:05 UTC
```cpp
#include <fmt/format.h>

int main()
{
    auto x = fmt::format(u8"{}", u8'a');

    for (auto const c : x) {
       fmt::print("{}", static_cast<char>(c));
    }
    fmt::print("\n");
}
```

The above program will format `u8'a'` as `97`, not `a`. Is this to be expected, WIP, or a bug?

**Comment by vitaut** [comment] 2019-06-02 19:13
Should print `a`. What compiler/flags? Seems to be working as expected on clang-1001.0.46.4 with `-std=c++2a`.

**Comment by vitaut** [comment] 2019-06-02 19:24
Should be covered by this case: https://github.com/fmtlib/fmt/blob/af2c73772ce8e06b266650849b4232c25d1fe63f/include/fmt/core.h#L800

**Comment by cjdb** [comment] 2019-06-02 19:36
> What compiler/flags?

For the above example, on my [Disco Docker][disco]:
```
root@acd1394df98b:/# g++-8 -std=c++2a -g -I fmt/include/ hello.cpp fmt/src/format.cc fmt/src/posix.cc -o hello
root@acd1394df98b:/# ./hello
a
root@acd1394df98b:/# g++-9 -std=c++2a -g -I fmt/include/ hello.cpp fmt/src/format.cc fmt/src/posix.cc -o hello
root@acd1394df98b:/# ./hello
97
```

Looks as though it's a GCC 9 regression.

[disco]: https://hub.docker.com/r/cjdb/cirrus-cpp

**Comment by vitaut** [comment] 2019-06-02 20:07
Could be some overload resolution weirdness, but I don't see how anything can be a better match than the `Char` overload above.

**Comment by vitaut** [comment] 2019-06-03 19:51
Actually argument capture works fine. The problem is in lower level functions that have never been updated to handle exotic character types: https://github.com/fmtlib/fmt/blob/7e42c65bb68adb32158a4ac2255413aa232a4e53/include/fmt/format.h#L2766

**Comment by vitaut** [comment] 2019-06-04 00:36
Fixed in https://github.com/fmtlib/fmt/commit/eddb84cfc06751c5623a9fe3e56fac101e8c317c.

**Closed by vitaut** 2019-06-04 00:36 UTC

**Comment by cjdb** [comment] 2019-06-05 18:41
Thanks!
