### ISSUE TITLE
CUDA, C++14, and GCC 6+

### ISSUE THREAD

**Issue by henryiii** [fmtlib/fmt#1080] opened 2019-03-15 17:36 UTC
Including the fmt header seems to kill nvcc compiling device code; I believe even if fmt is not used. This only starts happening if C++14 is turned on for host and device code (requires CUDA 9 or better).

Any ideas? I expect another check for CUDA needs to be added to the 1-2 that are already there.

```
/home/schreihf/git/fitting/goofit/extern/fmt/include/fmt/format.h(900): error: identifier "fmt::v5::internal::basic_data<void> ::ZERO_OR_POWERS_OF_10_32" is undefined in device code

/home/schreihf/git/fitting/goofit/extern/fmt/include/fmt/format.h(900): error: identifier "fmt::v5::internal::basic_data<void> ::ZERO_OR_POWERS_OF_10_32" is undefined in device code

/home/schreihf/git/fitting/goofit/extern/fmt/include/fmt/format.h(1158): error: identifier "Typeinfo for  ::fmt::v5::format_error" is undefined in device code

/home/schreihf/git/fitting/goofit/extern/fmt/include/fmt/format.h(900): error: identifier "fmt::v5::internal::basic_data<void> ::ZERO_OR_POWERS_OF_10_32" is undefined in device code

/home/schreihf/git/fitting/goofit/extern/fmt/include/fmt/format.h(900): error: identifier "fmt::v5::internal::basic_data<void> ::ZERO_OR_POWERS_OF_10_32" is undefined in device code

/home/schreihf/git/fitting/goofit/extern/fmt/include/fmt/format.h(1158): error: identifier "Typeinfo for  ::fmt::v5::format_error" is undefined in device code

/home/schreihf/git/fitting/goofit/extern/fmt/include/fmt/format.h(900): error: identifier "fmt::v5::internal::basic_data<void> ::ZERO_OR_POWERS_OF_10_32" is undefined in device code

/home/schreihf/git/fitting/goofit/extern/fmt/include/fmt/format.h(900): error: identifier "fmt::v5::internal::basic_data<void> ::ZERO_OR_POWERS_OF_10_32" is undefined in device code

/home/schreihf/git/fitting/goofit/extern/fmt/include/fmt/format.h(1158): error: identifier "Typeinfo for  ::fmt::v5::format_error" is undefined in device code

/home/schreihf/git/fitting/goofit/extern/fmt/include/fmt/format.h(772): error: identifier "fmt::v5::internal::basic_data<void> ::ZERO_OR_POWERS_OF_10_64" is undefined in device code

/home/schreihf/git/fitting/goofit/extern/fmt/include/fmt/format.h(772): error: identifier "fmt::v5::internal::basic_data<void> ::ZERO_OR_POWERS_OF_10_64" is undefined in device code

/home/schreihf/git/fitting/goofit/extern/fmt/include/fmt/format.h(1158): error: identifier "Typeinfo for  ::fmt::v5::format_error" is undefined in device code

/home/schreihf/git/fitting/goofit/extern/fmt/include/fmt/format.h(772): error: identifier "fmt::v5::internal::basic_data<void> ::ZERO_OR_POWERS_OF_10_64" is undefined in device code

/home/schreihf/git/fitting/goofit/extern/fmt/include/fmt/format.h(772): error: identifier "fmt::v5::internal::basic_data<void> ::ZERO_OR_POWERS_OF_10_64" is undefined in device code

/home/schreihf/git/fitting/goofit/extern/fmt/include/fmt/format.h(1158): error: identifier "Typeinfo for  ::fmt::v5::format_error" is undefined in device code

/home/schreihf/git/fitting/goofit/extern/fmt/include/fmt/format.h(900): error: identifier "fmt::v5::internal::basic_data<void> ::ZERO_OR_POWERS_OF_10_32" is undefined in device code

/home/schreihf/git/fitting/goofit/extern/fmt/include/fmt/format.h(900): error: identifier "fmt::v5::internal::basic_data<void> ::ZERO_OR_POWERS_OF_10_32" is undefined in device code

/home/schreihf/git/fitting/goofit/extern/fmt/include/fmt/format.h(1158): error: identifier "Typeinfo for  ::fmt::v5::format_error" is undefined in device code

/home/schreihf/git/fitting/goofit/extern/fmt/include/fmt/format.h(1178): error: identifier "Typeinfo for  ::fmt::v5::format_error" is undefined in device code

/home/schreihf/git/fitting/goofit/extern/fmt/include/fmt/format.h(772): error: identifier "fmt::v5::internal::basic_data<void> ::ZERO_OR_POWERS_OF_10_64" is undefined in device code

/home/schreihf/git/fitting/goofit/extern/fmt/include/fmt/format.h(772): error: identifier "fmt::v5::internal::basic_data<void> ::ZERO_OR_POWERS_OF_10_64" is undefined in device code

/home/schreihf/git/fitting/goofit/extern/fmt/include/fmt/format.h(1158): error: identifier "Typeinfo for  ::fmt::v5::format_error" is undefined in device code

Error: Internal Compiler Error (codegen): "there was an error in verifying the lgenfe output!"
```

fmt 5.3. Adding as subdirectory in CMake.  I have not been able to reproduce this yet in a small example.

**Comment by vitaut** [comment] 2019-03-16 23:31
Not sure. The definition of `ZERO_OR_POWERS_OF_10_32` doesn't depend on whether the code is compiled with C++14 or not, it's just a simple static member variable: https://github.com/fmtlib/fmt/blob/c21c6b8c4b89b3a3abc88ecec0ffbb76481db325/include/fmt/format-inl.h#L274

**Comment by henryiii** [comment] 2019-03-17 08:05
I’m going to keep investigating. I will report here with what I find.  So far, GCC 4.8 + C++11 works, and GCC 6 + C++14 fails.  A simple example seems to work fine, so it’s seems to be a change in behavior somewhere else

**Comment by vitaut** [comment] 2019-03-31 15:49
@henryiii, have you figured out what the problem is?

**Comment by henryiii** [comment] 2019-03-31 19:29
I've got two users who have seen this issue; one verified that if you rebuild everything with C++11 even with GCC 6, it works. So it's the change from 11 to 14 that triggers the issue. That's all I have so far, I've been traveling most of this month and will still be out till the 8th of April.

**Comment by vitaut** [comment] 2019-04-20 14:45
Closing since I don't think it's a bug in the library, but a PR to workaround the issue would be welcome.

**Closed by vitaut** 2019-04-20 14:45 UTC

**Comment by henryiii** [comment] 2019-04-20 14:48
OK, I’ll let you know if I find out anything.

**Comment by yves-dolce** [comment] 2019-05-31 20:25
Using the latest bit from the master branch, my project broke with Microsoft C++ compiler Version 19.21.27702.2 for x64:

```
error LNK2001: unresolved external symbol "public: static unsigned int const * const fmt::v5::internal::basic_data<void>::ZERO_OR_POWERS_OF_10_32" (?ZERO_OR_POWERS_OF_10_32@?$basic_data@X@internal@v5@fmt@@2QBIB)

error LNK2001: unresolved external symbol "public: static unsigned __int64 const * const fmt::v5::internal::basic_data<void>::ZERO_OR_POWERS_OF_10_64" (?ZERO_OR_POWERS_OF_10_64@?$basic_data@X@internal@v5@fmt@@2QB_KB)

error LNK2001: unresolved external symbol "public: static unsigned __int64 const * const fmt::v5::internal::basic_data<void>::ZERO_OR_POWERS_OF_10_64" (?ZERO_OR_POWERS_OF_10_64@?$basic_data@X@internal@v5@fmt@@2QB_KB)

error LNK2001: unresolved external symbol "public: static char const * const fmt::v5::internal::basic_data<void>::DIGITS" (?DIGITS@?$basic_data@X@internal@v5@fmt@@2QBDB)

error LNK2001: unresolved external symbol "public: static char const * const fmt::v5::internal::basic_data<void>::DIGITS" (?DIGITS@?$basic_data@X@internal@v5@fmt@@2QBDB)

error LNK2001: unresolved external symbol "public: static char const * const fmt::v5::internal::basic_data<void>::HEX_DIGITS" (?HEX_DIGITS@?$basic_data@X@internal@v5@fmt@@2QBDB)

error LNK2001: unresolved external symbol "public: static char const * const fmt::v5::internal::basic_data<void>::HEX_DIGITS" (?HEX_DIGITS@?$basic_data@X@internal@v5@fmt@@2QBDB)

error LNK2001: unresolved external symbol "public: static unsigned __int64 const * const fmt::v5::internal::basic_data<void>::POWERS_OF_10_64" (?POWERS_OF_10_64@?$basic_data@X@internal@v5@fmt@@2QB_KB)

error LNK2001: unresolved external symbol "public: static unsigned __int64 const * const fmt::v5::internal::basic_data<void>::POW10_SIGNIFICANDS" (?POW10_SIGNIFICANDS@?$basic_data@X@internal@v5@fmt@@2QB_KB)

error LNK2001: unresolved external symbol "public: static short const * const fmt::v5::internal::basic_data<void>::POW10_EXPONENTS" (?POW10_EXPONENTS@?$basic_data@X@internal@v5@fmt@@2QBFB)

```

**Comment by yves-dolce** [comment] 2019-05-31 21:43
Removing the template parameter in the definition seems to fix all of them but I don't know enough about the library and its testing to confirm this does not have an unwanted side-effect.

For 
```
template <>
const uint32_t basic_data<>::ZERO_OR_POWERS_OF_10_32[] = {0,
                                                           FMT_POWERS_OF_10(1)};
```

**Comment by vitaut** [comment] 2019-06-02 18:24
`format_data` is defined here: https://github.com/fmtlib/fmt/blob/5b7bbf88537f704005e3e71d9d4fda57e880e416/src/format.cc#L11

@yves-dolce, how do you link with {fmt}?
