### ISSUE TITLE
Visual studio 2019 compile error

### ISSUE THREAD

**Issue by imtrobin** [fmtlib/fmt#2965] opened 2022-07-05 05:24 UTC
Reporting, was using older fmt 5.x version fine.  Started working on a new project with latest master (fa2eb2d2e3ec5c21629f8ccd88ae05ec40b963fa), it has compile error (after removing module: in fmt.cc)

I'm able to put the old fmt 5.x in new project and compiles fine.

![image](https://user-images.githubusercontent.com/531606/177255343-d77df0b5-8d99-4ed5-ba0f-4eb73470a330.png)

**Comment by vitaut** [comment] 2022-07-05 13:19
Please provide a self-contained repro, ideally on godbolt.

**Comment by imtrobin** [comment] 2022-07-06 01:37
Unfortunately, it's a Unreal engine project, it's using MSBuild and the dependencies is 100GB. I tried in a new C++ hello world, it can compile. Is there some compiler flags needed?

**Comment by vitaut** [comment] 2022-07-06 02:33
{fmt} doesn't need any special flags, only C++11 support. I recommend comparing build flags between your working example  and the one that gives errors.

**Comment by vitaut** [comment] 2022-07-06 14:21
Closing as this looks like a configuration error but feel free to reopen if you have a repro.

**Closed by vitaut** 2022-07-06 14:21 UTC

**Comment by ridilculous** [comment] 2022-09-25 09:07
I'm observing the same problem.
The cause is that Unreal Engine has a macro definition for `check` which is always visible due to their way of handling global includes. (they also have one for `verify`)

It would be possible to `#undef check` before every `#include <fmt/...>` or create some wrapper includes doing this but that'd be awful.
I know it sucks but i'd like to ask if you could change all check names to something unique to format? I'd happily provide a PR for this.

Because you need a installed Unreal Engine it's impossible to create a live example.
Offline reproduction is easy: Create a unreal engine project, add fmt in the global includes or copy/paste all the headers into your project and add a #include <fmt/format.h> somewhere; then build.

For completeness sake, here's what MSVC is complaining about without `#undef check`:
```
fmt\core.h(1358): error C4346: 'std::is_integral<V>::value': dependent name is not a type
fmt\core.h(1358): note: prefix with 'typename' to indicate a type
fmt\core.h(1363): note: see reference to class template instantiation 'fmt::v9::detail::has_format_as<T>' being compiled
fmt\core.h(1359): error C2988: unrecognizable template declaration/definition
fmt\core.h(1359): error C2059: syntax error: '<end Parse>'
fmt\core.h(1359): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
fmt\core.h(1359): error C2988: unrecognizable template declaration/definition
fmt\core.h(1359): error C2059: syntax error: '->'
fmt\core.h(1359): error C2238: unexpected token(s) preceding ';'
fmt\core.h(1360): error C2062: type 'auto' unexpected
fmt\core.h(1360): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
fmt\core.h(1360): error C2988: unrecognizable template declaration/definition
fmt\core.h(1360): error C2059: syntax error: '->'
fmt\core.h(1360): error C2238: unexpected token(s) preceding ';'
fmt\core.h(1362): error C2332: 'enum': missing tag name
fmt\core.h(1362): error C3306: 'fmt::v9::detail::has_format_as<T>::<unnamed-tag>': unnamed class template is not allowed

```

**Comment by vitaut** [comment] 2022-09-25 13:47
We are not adding workarounds for random third-party macros.

**Comment by vampy** [comment] 2022-11-22 09:51
Just hit this issue with fmt 9.1.0 and unreal 5.0.3, please consider renaming `check` to something else.

**Comment by vampy** [comment] 2022-11-22 18:58
I just did  workaround
```
#pragma push_macro("check")
#undef check

#include <fmt/format.h>

#pragma pop_macro("check")
```
