### ISSUE TITLE
Building a GTK app with 11.0.1

### ISSUE THREAD

**Issue by GaryElshaw** [fmtlib/fmt#4052] opened 2024-07-06 06:42 UTC
All of the various Transmission clients are compiling fine with the exception of GTK. Any help would be appreciated.

![image](https://github.com/fmtlib/fmt/assets/69029666/dcb0dbec-7cda-461c-ab8e-17e266ac5177)

**Comment by vitaut** [comment] 2024-07-06 13:03
As the error says, mixing character (code unit) types is disallowed in {fmt}. In this case the format string is a `char` string and `action_name` is a `Glib::ustring` which uses a different code unit type. To fix this you'll need provide conversion from one to the other or a formatter that does the conversion.

**Comment by GaryElshaw** [comment] 2024-07-06 14:39
Is there a change i can report back to the team for future reference? All previous versions of fmt have been working fine.

**Comment by vitaut** [comment] 2024-07-06 17:09
Reopening to investigate further since it worked in an earlier version. Could you provide a repro?

**Comment by vitaut** [comment] 2024-07-06 17:24
I managed to repro the issue: https://www.godbolt.org/z/eqbjx97Kx. The problem is that `ustring` is incorrectly detected as as `std::string`.

**Comment by Coeur** [comment] 2024-07-06 18:59
Testing commit by commit, it seems to me that the build regression came with 800a0bb23f0bb45bfabecb4236bd1a3f40f9632d.

**Comment by GaryElshaw** [comment] 2024-07-06 19:31
@vitaut Is this a change you think Transmission needs to address, or something for fmt to look at?

**Comment by vitaut** [comment] 2024-07-06 19:49
It's a bug in {fmt}, we shouldn't treat `ustring` as `std::string`. I'll submit a fix.

**Comment by GaryElshaw** [comment] 2024-07-06 19:56
Thank you!

**Comment by vitaut** [comment] 2024-07-06 21:03
Should be fixed in https://github.com/fmtlib/fmt/commit/7a8b54a0ef7ca1791b0a5491b6e0593e1cf2dd5e. Could you verify it?

**Comment by Coeur** [comment] 2024-07-06 21:45
Verified successful. Thank you. Sorry for only pointing this out after the 11.0.1 release instead of before.

**Closed** 2024-07-06 21:48 UTC
