### ISSUE TITLE
-Walloc-size-larger-than= in format.h:943 with gcc 12.2.1 and Intel sgx-sdk

### ISSUE THREAD

**Issue by bmildner-xt** [fmtlib/fmt#3719] opened 2023-11-15 14:13 UTC
After updating from fmt version 9.1.0 to 10.1.1 we see the following warning from gcc 12.2.1 when compiling code for use in an Intel SGX enclave:
```
In file included from /opt/intel/sgxsdk/include/libcxx/memory:673,
                 from /opt/intel/sgxsdk/include/libcxx/algorithm:653,
                 from /home/xyz/CLionProjects/vau3/shadowline/src/utils/hex.h:3,
                 from /home/xyz/CLionProjects/vau3/shadowline/src/utils/hex.cpp:1:
In function ‘void* std::__1::__libcpp_operator_new(_Args ...) [with _Args = {long unsigned int}]’,
    inlined from ‘void* std::__1::__libcpp_allocate(size_t, size_t)’ at /opt/intel/sgxsdk/include/libcxx/new:269:31,
    inlined from ‘constexpr _Tp* std::__1::allocator<_Tp>::allocate(size_t) [with _Tp = unsigned int]’ at /opt/intel/sgxsdk/include/libcxx/memory:876:62,
    inlined from ‘static constexpr std::__1::allocator_traits<_Alloc>::pointer std::__1::allocator_traits<_Alloc>::allocate(allocator_type&, size_type) [with _Alloc = std::__1::allocator<unsigned int>]’ at /opt/intel/sgxsdk/include/libcxx/__memory/allocator_traits.h:260:28,
    inlined from ‘void fmt::v10::basic_memory_buffer<T, SIZE, Allocator>::grow(size_t) [with T = unsigned int; long unsigned int SIZE = 32; Allocator = std::__1::allocator<unsigned int>]’ at /home/xyz/CLionProjects/vau3/shadowline/cmake-build-release/_deps/fmt-src/include/fmt/format.h:943:51:
/opt/intel/sgxsdk/include/libcxx/new:245:24: error: argument 1 value ‘18446744073709551612’ exceeds maximum object size 9223372036854775807 [-Werror=alloc-size-larger-than=]
  245 |   return ::operator new(__args...);
      |          ~~~~~~~~~~~~~~^~~~~~~~~~~
```
Strangely this warning is only triggered in our release build although we use the same warning settings for all builds ...

Adding a `detail::assume(new_capacity <= max_size);` in format.h:942 (above the allocate) silences gcc.

RHEL 8.8
gcc 12.2.1
fmt 10.1.1 (or current master)
Intel sgx-sdk 2.21

**Comment by vitaut** [comment] 2023-11-15 18:00
Looks like a gcc bug (or at least a false positive), we've seen a bunch of these with gcc 12. Does the warning reproduces with gcc 13?

**Comment by bmildner-xt** [comment] 2023-11-17 10:37
Yes, it does (gcc 13.1.1 on RHEL 8.9)!
The `detail::assume(new_capacity <= max_size);` still suppresses it.

**Comment by vitaut** [comment] 2023-11-18 16:59
Could you provide a godbolt repro? I tried to put one together but the warning doesn't seem to have any effect even on simpler code (https://godbolt.org/z/nEc7q7j1n).

**Comment by vitaut** [comment] 2023-11-22 21:03
Closing as it doesn't look like a bug in {fmt}. Even if we were passing ridiculously large value to `allocator::allocate` it should throw instead of forwarding to `new` and triggering a warning: https://eel.is/c++draft/allocator.members. I recommend reporting to your compiler/library vendor. As a workaround you can suppress the warning with `FMT_SYSTEM` or other means.

**Closed by vitaut** 2023-11-22 21:03 UTC
