### ISSUE TITLE
Potential performance regression of vformat_to in libfmt 11 compared to libfmt 10.2.1

### ISSUE THREAD

**Issue by odygrd** [fmtlib/fmt#4070] opened 2024-07-12 13:23 UTC
Hello,

I am experiencing a drop in throughput when migrating my logging library to libfmt 11 compared to libfmt 10.2.1.

I haven't been able to figure out yet if this is something related to my project or the newer version of libfmt, but the only change is the libfmt library.

Environment
Compiler: GCC 13
OS: Linux RHEL
Build Configuration: Release build with -O3 -DNDEBUG -std=gnu++20
libfmt: Header-only version

```c++

#include "quill/bundled/fmt/base.h"
#include "quill/bundled/fmt/format.h"

#include <string>
#include <iostream>
#include <chrono>
#include <atomic>

void ClobberMemory() {
  std::atomic_signal_fence(std::memory_order_acq_rel);
}

int main()
{
  using format_buffer_t = fmt::basic_memory_buffer<char>;

  fmt::string_view format_str = "Hello, {}. The answer is {} and {}.";

  int a = 1;
  int b = 2345;
  int c = 6789;
  auto args = fmt::make_format_args(a, b, c);

  const int n = 10'000'000;

  auto start = std::chrono::high_resolution_clock::now();

  for (int iteration = 0; iteration < n; ++iteration)
  {
    format_buffer_t buffer;
    fmt::vformat_to(std::back_inserter(buffer), format_str, args);
  }

  ClobberMemory();

  auto end = std::chrono::high_resolution_clock::now();

  std::chrono::duration<double> duration = end - start;
  double total_time = duration.count() * 1000;  // Convert to milliseconds

  std::cout << "Total time for formatting " << n << " strings: "
            << total_time << " ms" << std::endl;

  return 0;
}
```

I ran the above several times for both versions and it seems that version 10.2.1 is always faster. I am running it on an isolated cpu and nothing else is running on the whole box

<img width="380" alt="image" src="https://github.com/user-attachments/assets/210b4fa3-8343-43e6-9140-9ec4663a77df">

Are there any known changes in libfmt 11 that could explain this difference?

**Comment by vitaut** [comment] 2024-07-12 19:30
There was a temporary regression in https://github.com/fmtlib/fmt/commit/f348d1a211bcfa8c6f70195d91ad3ae783b64130 that was mostly fixed in https://github.com/fmtlib/fmt/commit/f348d1a211bcfa8c6f70195d91ad3ae783b64130 but it looks like it wasn't completely fixed.

**Comment by vitaut** [comment] 2024-07-12 20:41
Basically we need to reintroduce the detection of `back_insert_iterator<buffer>` which was accidentally dropped.

**Comment by vitaut** [comment] 2024-07-13 15:15
Done in https://github.com/fmtlib/fmt/commit/33e7ed1eb5bbbd80ab4efb5495dff54dd1d83de6.

Before:
```
Total time for formatting 10000000 strings: 664.418 ms
```

After:
```
Total time for formatting 10000000 strings: 618.701 ms
```

This fixes most of the regression, will look into the remaining discrepancy.

**Comment by vitaut** [comment] 2024-07-14 20:21
The regression should be fixed as of https://github.com/fmtlib/fmt/commit/f29a7e7970349eec2c76f3c0eda3d5accdd3aa6b.

10.2.1:
```
Total time for formatting 10000000 strings: 527.554 ms
```

f29a7e7970349eec2c76f3c0eda3d5accdd3aa6b:
```
Total time for formatting 10000000 strings: 525.269 ms
```
(again, best of 3 runs)

Thanks for catching this!

**Closed by vitaut** 2024-07-14 20:21 UTC
