### ISSUE TITLE
Build error "fmt/bundled/format.h:447:58: error: ‘_ecvt_s’ was not declared in this scope" on Unbuntu 17.10 (glibc 2.26)

### ISSUE THREAD

**Issue by svadum** [fmtlib/fmt#674] opened 2018-03-09 09:41 UTC
```
static bool isnegative(double x)
    {
        using namespace fmt::internal;
        if (const_check(sizeof(signbit(x)) == sizeof(bool) ||
                        sizeof(signbit(x)) == sizeof(int)))
        {
            return signbit(x) != 0;
        }
        if (x < 0) return true;
        if (!isnotanumber(x)) return false;
        int dec = 0, sign = 0;
        char buffer[2];  // The buffer size must be >= 2 or _ecvt_s will fail.
        _ecvt_s(buffer, sizeof(buffer), x, 0, &dec, &sign); // glibc 2.26 - error: ‘_ecvt_s’ was not declared in this scope
        return sign != 0;
    }
```

**Comment by vitaut** [comment] 2018-03-12 12:42
@svadum, could you post the code to reproduce this error? It looks like you are using the version of {fmt} bundled with spdlog but I was not able to repro the error on `libspdlog-dev` on Ubuntu 17.10.

**Comment by svadum** [comment] 2018-03-12 12:51
Hi, thanks for the reply.
Yes you're right, I am using spdlog library. At this time, I have no ability to show the code, but I will try to update the version of spdlog and write about the result a little later.

**Comment by Kronuz** [comment] 2018-03-17 18:27
Apparently, the dummy implementations of system functions such as `_ecvt_s` are declared inside the namespace `fmt::internal`, but used inside `std`. If the system functions are not available, maybe it should use those, but instead `error: ‘_ecvt_s’ was not declared in this scope` error will be emitted.

**Comment by vitaut** [comment] 2018-03-17 19:01
@Kronuz do you get similar error in which case could you provide an example that triggers it?

**Comment by Kronuz** [comment] 2018-03-20 22:42
@vitaut, nope, sorry... I was just guessing, since I saw the dummy functions were in a different namespace.

**Comment by vitaut** [comment] 2018-03-21 13:16
Closing for now, but feel free to reopen with details on how to repro.

**Closed by vitaut** 2018-03-21 13:16 UTC
