### ISSUE TITLE
Migration from 7.1.2 to 8.0.1 and ostream.h gcc errors

### ISSUE THREAD

**Issue by btmcg** [fmtlib/fmt#2419] opened 2021-07-08 19:43 UTC
I'm currently attempting to migrate from fmt 7.1.2 to 8.0.1 and I'm getting a ton of errors using gcc 10.2.0 and gcc 11.1.0. Note that the code compiles without issue using clang 12.0.0.

I have yet been able to reproduce a bite-sized code snippet to reproduce the issue, but in my extensive codebase, the issue occurs with any struct/class where we rely on the insertion operator for string conversions. The error I see is this:

```
.../fmt/8.0.1/gcc-11.1.0/include/fmt/ostream.h:123:8: error: partial specialization of 'struct fmt::v8::detail::fallback_formatter<T, Char, typename std::enable_if<fmt::v8::detail::is_streamable<T, Char>::value, void>::type>' after instantiation of 'struct fmt::v8::detail::fallback_formatter<std::__cxx11::basic_string<char>, char, void>' [-fpermissive]
  123 | struct fallback_formatter<T, Char, enable_if_t<is_streamable<T, Char>::value>>
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Again, this code all compiles without issue in Clang, so it seems to me like a GCC issue (perhaps GCC is less forgiving?), however I'm definitely not ruling out issues in my codebase. Any help on investigating and troubleshooting this issue would be a great help. Thanks!

**Comment by vitaut** [comment] 2021-07-08 20:55
It's hard to tell what's wrong from this error alone but instantiation of `fallback_formatter` for `std::string` looks suspicious. Normally it shouldn't happen because `std::string` formatting goes through normal, not fallback formatter.

**Comment by btmcg** [comment] 2021-07-08 21:00
@vitaut I totally understand that I didn't give much info to go on. In fact, it was only through commenting out all inclusions of `fmt/ostream.h` that I was able to determine that this error is caused for any custom struct/class with an insertion operator defined and being used. Any sample code I've written seems to work fine, but I can't get passed this with gcc. I'm happy to experiment if anyone has any thoughts as to what might lead to more information.

**Comment by vitaut** [comment] 2021-07-21 15:18
Closing for now but feel free to reopen with a repro.

**Closed by vitaut** 2021-07-21 15:18 UTC

**Comment by timblechmann** [comment] 2021-09-27 10:05
@vitaut, while i don't have a reduced test case, some observations:

* `gcc-10.3.0`/x86_64/ubuntu accepts the code
* `gcc-10.2.0`/armv7/yocto fails with the "partial specialization" error
* `gcc-11.1.0`/x86_64/ubuntu

it seems to be related to `consteval`: if i disable consteval, gcc-10.2 accepts the code

**Comment by Jerry-Ma** [comment] 2021-10-23 01:47
I believe I am now seeing this error with GCC 11.2 and C++20. Here is an example showing the issue: https://godbolt.org/z/G66qW11zh

It turns out that the include order matters in this case:

```
#include <fmt/format.h>

// #include <fmt/ostream.h>  // when this line is here, it works

constexpr static auto a = std::string_view{"this is some value a"};

struct A {

    auto f() {return fmt::format("{}", a);}
};

#include <fmt/ostream.h>  // when this line is here, it does not work

struct B {

    template <typename OStream>
    friend auto operator<<(OStream &os, const B &b)
        -> decltype(auto) {
        return os << fmt::format("A({})", b.value);

    }

    constexpr static std::string_view value{"This some value in B"};
};


int main () {

fmt::print("{}\n", A{}.f());

fmt::print("{}\n", B{});

}
```

**Comment by wc222** [comment] 2021-11-15 03:51
@Jerry-Ma Thanks very much. I included `fmt/core.h` and `fmt/ostream.h` together always, then it passed the compiling (gcc-10)

**Comment by gdmsl** [comment] 2021-12-10 13:17
I had the same problem happening to me with `clang version 13.0.0` on Linux.  Fixed in the same way as @wc222, by including `fmt/core.h` and `fmt/ostream.h` together everywhere.

**Comment by alexezeder** [comment] 2021-12-10 14:12
Looks like [an example](https://github.com/fmtlib/fmt/issues/2419#issuecomment-950037851) from @Jerry-Ma works now, since it's more or less the same as in https://github.com/fmtlib/fmt/issues/2638. Compile explorer also [confirms that](https://godbolt.org/z/G66qW11zh).
Considering that and different compiler, @gdmsl, are you sure you faced the same issue?

**Comment by gdmsl** [comment] 2021-12-10 14:28
I am sorry. I checked the build folder since I was not able to reproduce a third time. My CMake configuration was not respecting the compiler choice. Sorry for the noise. Should I remove the previous comment?

**Comment by alexezeder** [comment] 2021-12-10 15:14
> Sorry for the noise. Should I remove the previous comment?

Don't worry, that's fine 🙂
