### ISSUE TITLE
Undefined reference __imp__ZN3fmt2v58internal10basic_dataIvE6DIGITSE when using DLL on MinGW

### ISSUE THREAD

**Issue by HazardyKnusperkeks** [fmtlib/fmt#1204] opened 2019-06-23 20:33 UTC
Hi,

I'm using MinGW 8.1 to build fmt as dll and then using it. I'm defining `FMT_EXPORT` for building of the dll, and `FMT_SHARED` for the using projects.
I have updated my copy and now I'm getting 

> \<file>:(.text+0x147): undefined reference to `__imp__ZN3fmt2v58internal10basic_dataIvE6DIGITSE'

etc., I think this is related to the commit 29c10fbf6e51d2a204f7c24c90d7ccec86cc659a

My fix is just `#    define FMT_EXTERN_TEMPLATE_API FMT_API` in any case.
Also I'm getting a warning

> \fmt\src\format.cc:11: Warnung: type attributes ignored after type is already defined [-Wattributes]
 template struct FMT_API internal::basic_data<void>;
                                   ^~~~~~~~~~~~~~~~

which disappears if I remove FMT_API in the .cc.

**Comment by HazardyKnusperkeks** [comment] 2019-06-24 17:53
The above only makes it compile and link. But I get a crash at runtime (not even debuggable), for now I have additionally removed the extern template instantiation for void.

**Comment by vitaut** [comment] 2019-06-26 17:26
I don't have a Windows machine at hand to debug this, but a PR is welcome. You could also use a static library which is the default and recommended build configuration.

**Comment by vedranmiletic** [comment] 2019-07-26 11:18
@vitaut if you have a Linux machine, you can use the MinGW cross-compiler which exhibits the same issue (both 32-bit and 64-bit).

Static build indeed works fine.

**Comment by bbolli** [comment] 2019-08-26 21:47
@vitaut:
> You could also use a static library which is the default and recommended build configuration.

Should packages (like the mingw one) build the shared library at all? Or just the static one to push users to the recommended usage?

**Comment by luncliff** [comment] 2019-08-28 10:37
@HazardyKnusperkeks have you tried the CMake's symbol exporting?
This exports all symbols in `.dll` to `.lib`. Like `__attribute__((visibility("default")))`.

```cmake
set_target_properties(fmt
PROPERTIES
    WINDOWS_EXPORT_ALL_SYMBOLS  true
)
```

**Comment by HazardyKnusperkeks** [comment] 2019-08-29 13:53
> 
> 
> @HazardyKnusperkeks have you tried the CMake's symbol exporting?
> This exports all symbols in `.dll` to `.lib`. In short, it works like `__attribute__((visibility("default")))`.
> 
> ```cmake
> set_target_properties(fmt
> PROPERTIES
>     WINDOWS_EXPORT_ALL_SYMBOLS  true
> )
> ```
> 
> I'm not sure it will work for MinGW, but it did for my 'clang-cl' related works.

I've not tried anything apart from what I mentioned in the opening. Because I currently have not much time for my private coding and in the company code we don't use fmt yet.

Apart from that I don't use CMake at all.

**Comment by vitaut** [comment] 2019-11-17 16:22
Looks like a GCC bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=50044. A possible workaround is to define `FMT_EXTERN_TEMPLATE_API` to `FMT_API` on MinGW or use a static library. Closing as this is not a bug in {fmt} but would be happy to accept a PR to workaround the issue.

**Closed by vitaut** 2019-11-17 16:22 UTC
