### ISSUE TITLE
enum class is treated as int under gcc/clang

### ISSUE THREAD

**Issue by ShaderManager** [fmtlib/fmt#1424] opened 2019-11-27 12:15 UTC
https://godbolt.org/z/VZUd--

fmtlib v6.0.0:
fmtlib under clang/gcc formats `enum class` as `int` when there is no overloaded `operator <<` for this type. MSVC emits error `don't know how to format the type`
fmtlib v5.3.0:
all major compilers (clang, gcc, msvc) emit error `don't know how to format the type`

Is there some regression between v5.3.0 and v6.0.0 related to this issue?

**Comment by vitaut** [comment] 2019-11-27 16:23
Good catch. Looks like regression was introduced in #1286. A cast should be replaced with an implicit conversion.

**Comment by vitaut** [comment] 2019-11-27 19:07
Should be fixed in https://github.com/fmtlib/fmt/commit/9a37d5f38c8acbdff6f931faadbb9586d4864846.

**Comment by vitaut** [comment] 2021-11-25 14:46
Looks like there was a regression.

**Comment by vitaut** [comment] 2021-12-09 20:28
The regression has been fixed in https://github.com/fmtlib/fmt/commit/fd62fba9855c9cf8fe17eb9363e03f93563d9dc3.

**Closed by vitaut** 2021-12-09 20:28 UTC
