### ISSUE TITLE
some locale tests fails with gcc12 on musl

### ISSUE THREAD

**Issue by a16bitsysop** [fmtlib/fmt#3049] opened 2022-08-20 07:32 UTC
gcc 12 on alpine includes this patch:
https://git.alpinelinux.org/aports/tree/main/gcc/0043-libstdc-do-not-throw-exceptions-for-non-C-locales-on.patch?h=12085c3cad1699b0e

previously these tests were skipped if they crashed, but now they are not skipped.

```
[ RUN      ] chrono_test.weekday
/builds/alpine/aports/community/fmt/src/fmt-9.0.0/test/chrono-test.cc:581: Failure
Value of: (std::vector<std::string>{"пн", "Пн", "пнд", "Пнд"})
Expected: contains at least one element that is equal to "Mon"
  Actual: { "\xD0\xBF\xD0\xBD"
    As Text: "пн", "\xD0\x9F\xD0\xBD"
    As Text: "Пн", "\xD0\xBF\xD0\xBD\xD0\xB4"
    As Text: "пнд", "\xD0\x9F\xD0\xBD\xD0\xB4"
    As Text: "Пнд" }
/builds/alpine/aports/community/fmt/src/fmt-9.0.0/test/chrono-test.cc:583: Failure
Value of: (std::vector<std::string>{"пн", "Пн", "пнд", "Пнд"})
Expected: contains at least one element that is equal to "Mon"
  Actual: { "\xD0\xBF\xD0\xBD"
    As Text: "пн", "\xD0\x9F\xD0\xBD"
    As Text: "Пн", "\xD0\xBF\xD0\xBD\xD0\xB4"
    As Text: "пнд", "\xD0\x9F\xD0\xBD\xD0\xB4"
    As Text: "Пнд" }
[  FAILED  ] chrono_test.weekday (0 ms)
```

and 

```
[ RUN      ] unicode_test.legacy_locale
/builds/alpine/aports/community/fmt/src/fmt-9.0.0/test/unicode-test.cc:46: Failure
Value of: (std::vector<std::string>{"День недели: пн", "День недели: Пн"})
Expected: contains at least one element that is equal to "\xD0\x94\xD0\xB5\xD0\xBD\xD1\x8C \xD0\xBD\xD0\xB5\xD0\xB4\xD0\xB5\xD0\xBB\xD0\xB8: Mon"
    As Text: "День недели: Mon"
  Actual: { "\xD0\x94\xD0\xB5\xD0\xBD\xD1\x8C \xD0\xBD\xD0\xB5\xD0\xB4\xD0\xB5\xD0\xBB\xD0\xB8: \xD0\xBF\xD0\xBD"
    As Text: "День недели: пн", "\xD0\x94\xD0\xB5\xD0\xBD\xD1\x8C \xD0\xBD\xD0\xB5\xD0\xB4\xD0\xB5\xD0\xBB\xD0\xB8: \xD0\x9F\xD0\xBD"
    As Text: "День недели: Пн" }
[  FAILED  ] unicode_test.legacy_locale (0 ms)
```

and

```
[ RUN      ] locale_test.chrono_weekday
/builds/alpine/aports/community/fmt/src/fmt-9.0.0/test/xchar-test.cc:490: Failure
Value of: (std::vector<std::wstring>{L"\x43F\x43D", L"\x41F\x43D", L"\x43F\x43D\x434", L"\x41F\x43D\x434"})
Expected: contains at least one element that is equal to L"Mon"
  Actual: { L"\x43F\x43D", L"\x41F\x43D", L"\x43F\x43D\x434", L"\x41F\x43D\x434" }
[  FAILED  ] locale_test.chrono_weekday (0 ms)
```

Full output here:
https://gitlab.alpinelinux.org/alpine/aports/-/jobs/804609/raw

**Comment by nekopsykose** [comment] 2022-08-20 08:10
more specifically, before they would print:  

```
/tmp/fmt # ./bin/unicode-test 
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from unicode_test
[ RUN      ] unicode_test.is_utf8
[       OK ] unicode_test.is_utf8 (0 ms)
[ RUN      ] unicode_test.legacy_locale
ru_RU.CP1251 locale is missing.
[       OK ] unicode_test.legacy_locale (1 ms)
[----------] 2 tests from unicode_test (1 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test suite ran. (1 ms total)
[  PASSED  ] 2 tests.
```

this is because https://github.com/fmtlib/fmt/blob/883d9595c53101f5d32f86bceb496676cd3413c2/test/util.cc#L30-L46  

returns a default locale on runtime error. that above runtime error is hit with any non-C locale (even `C.UTF-8`!) with musl libstdc++ with the generic posix locale backend, but this is generally not fun because having any LANG set or the like makes any program fail on startup if they do any locale-related things (and the locale \*does work* for C since it gets passed through to C and whatever normally). so, the libstdc++ patch makes it not throw (but clearly breaks this part instead). this is very musl specific (and doesn't seem like an fmt issue at all), not sure if there's anything to be done here (actual fixes should be in libstdc++).

**Comment by vitaut** [comment] 2022-08-20 13:58
Lying about the locale is clearly a broken behavior on the musl part so I recommend reporting there. A PR with a workaround would be welcome too, we already have one in this test which can be generalized.

**Comment by nekopsykose** [comment] 2022-08-20 15:08
technically it's not the musl part but the libstdc++ locale part- all of them are lying to be valid (no throw). i guess in the meantime the patch should be amended to throw on everything that isn't 'C' or '*.UTF-8' - musl only supports UTF-8 locales (so even with everything working in libstdc++, the `ru_RU.CP1251` locale should throw the invalid locale error). with that, these tests would go back to passing, and only unsupported locales should throw (correctly)..  

@ericonr i think you recall this libstdc++ patch above. do you think a comparison for *UTF-8 or C in libstdc++ makes more sense than everything-is-valid-always?

**Comment by vitaut** [comment] 2022-08-20 16:36
Closing as this is not a bug in {fmt}. Hopefully this can be resolved in Alpine by (partially) reverting the problematic patch.

**Closed by vitaut** 2022-08-20 16:36 UTC
