### ISSUE TITLE
Sanitizer error at compile time

### ISSUE THREAD

**Issue by stayprivate** [fmtlib/fmt#2428] opened 2021-07-19 18:22 UTC
GCC 9.3 with almost all sanitizer's options turned on, at COMPILE time I get the following warning when compiling format.cc from 8.0.1.0.  That's on Ubuntu 20.  Apparently it's a bug in gcc (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=97145).  I removed -fsanitize=pointer-compare -fsanitize=pointer-subtract. I though maybe you would want do document this ?

FAILED: std_c/CMakeFiles/std_c.dir/__/fmt/src/format.cc.o 
/usr/lib/icecc/bin/g++-9 -DFMT_USE_FULL_CACHE_DRAGONBOX=1 -I../../fmt/include -Iinclude -O0 -g2 -DDEBUG=1 -Werror -Wno-array-bounds -fstack-protector-all   -Wall -Wnarrowing -Wformat -Wno-format-y2k -Wno-enum-compare -Wunused-parameter -Woverloaded-virtual -Wextra -Wnon-virtual-dtor -Wno-sign-promo -Wno-unused-result -Wno-nonnull -Wno-maybe-uninitialized -fmax-errors=30 -msse4.2 -mfpmath=sse -march=nehalem -mtune=sandybridge -funsigned-char -fexceptions -Wstrict-null-sentinel -Wlogical-op -fstack-protector-all -fno-omit-frame-pointer -fsanitize=address -fsanitize=undefined -fsanitize=shift -fsanitize=shift-base -fsanitize=shift-exponent -fsanitize=unreachable -fsanitize=vla-bound -fsanitize=return -fsanitize=null -fsanitize=signed-integer-overflow -fsanitize=bounds -fsanitize=bounds-strict -fsanitize=object-size -fsanitize=float-divide-by-zero -fsanitize=float-cast-overflow -fsanitize=nonnull-attribute -fsanitize=returns-nonnull-attribute -fsanitize=bool -fsanitize=enum -fsanitize=vptr -fsanitize=pointer-compare -fsanitize=pointer-subtract -fsanitize=pointer-overflow -fsanitize=builtin -Wno-missing-field-initializers -std=gnu++17  -Wno-switch-default -MD -MT std_c/CMakeFiles/std_c.dir/__/fmt/src/format.cc.o -MF std_c/CMakeFiles/std_c.dir/__/fmt/src/format.cc.o.d -o std_c/CMakeFiles/std_c.dir/__/fmt/src/format.cc.o -c ../../fmt/src/format.cc
In file included from ../../fmt/include/fmt/format.h:44,
                 from ../../fmt/include/fmt/format-inl.h:29,
                 from ../../fmt/src/format.cc:8:
../../fmt/include/fmt/core.h: In instantiation of ‘void fmt::v8::detail::check_format_string(S) [with <template-parameter-1-1> = {fmt::v8::basic_string_view<char>&, const char (&)[3]}; S = fmt::v8::detail::format_error_code(fmt::v8::detail::buffer<char>&, int, fmt::v8::string_view)::<lambda()>::FMT_COMPILE_STRING; typename std::enable_if<fmt::v8::is_compile_string<S>::value, int>::type <anonymous> = 0]’:
../../fmt/include/fmt/core.h:2848:41:   required from ‘fmt::v8::basic_format_string<Char, Args>::basic_format_string(const S&) [with S = fmt::v8::detail::format_error_code(fmt::v8::detail::buffer<char>&, int, fmt::v8::string_view)::<lambda()>::FMT_COMPILE_STRING; typename std::enable_if<std::is_convertible<const S&, fmt::v8::basic_string_view<Char> >::value, int>::type <anonymous> = 0; Char = char; Args = {fmt::v8::basic_string_view<char>&, const char (&)[3]}]’
../../fmt/include/fmt/format-inl.h:74:51:   required from here
../../fmt/include/fmt/core.h:2729:33:   in ‘constexpr’ expansion of ‘fmt::v8::detail::parse_format_string<true, char, fmt::v8::detail::format_string_checker<char, fmt::v8::detail::error_handler, fmt::v8::basic_string_view<char>, char [3]> >(s, fmt::v8::detail::format_string_checker<char, fmt::v8::detail::error_handler, fmt::v8::basic_string_view<char>, char [3]>(s, (fmt::v8::detail::error_handler(), fmt::v8::detail::error_handler())))’
../../fmt/include/fmt/core.h:2389:11: error: ‘__builtin___sanitizer_ptr_sub((((const char*)"{}{}") + 4), ((const char*)"{}{}"))’ is not a constant expression
 2389 |   if (end - begin < 32) {
      |       ~~~~^~~~~~~
../../fmt/include/fmt/core.h: In instantiation of ‘void fmt::v8::detail::check_format_string(S) [with <template-parameter-1-1> = {const char (&)[7], int&}; S = fmt::v8::detail::format_error_code(fmt::v8::detail::buffer<char>&, int, fmt::v8::string_view)::<lambda()>::FMT_COMPILE_STRING; typename std::enable_if<fmt::v8::is_compile_string<S>::value, int>::type <anonymous> = 0]’:
../../fmt/include/fmt/core.h:2848:41:   required from ‘fmt::v8::basic_format_string<Char, Args>::basic_format_string(const S&) [with S = fmt::v8::detail::format_error_code(fmt::v8::detail::buffer<char>&, int, fmt::v8::string_view)::<lambda()>::FMT_COMPILE_STRING; typename std::enable_if<std::is_convertible<const S&, fmt::v8::basic_string_view<Char> >::value, int>::type <anonymous> = 0; Char = char; Args = {const char (&)[7], int&}]’
../../fmt/include/fmt/format-inl.h:75:58:   required from here
../../fmt/include/fmt/core.h:2729:33:   in ‘constexpr’ expansion of ‘fmt::v8::detail::parse_format_string<true, char, fmt::v8::detail::format_string_checker<char, fmt::v8::detail::error_handler, char [7], int> >(s, fmt::v8::detail::format_string_checker<char, fmt::v8::detail::error_handler, char [7], int>(s, (fmt::v8::detail::error_handler(), fmt::v8::detail::error_handler())))’
../../fmt/include/fmt/core.h:2389:11: error: ‘__builtin___sanitizer_ptr_sub((((const char*)"{}{}") + 4), ((const char*)"{}{}"))’ is not a constant expression
../../fmt/include/fmt/core.h: In instantiation of ‘void fmt::v8::detail::check_format_string(S) [with <template-parameter-1-1> = {unsigned int&}; S = fmt::v8::formatter<fmt::v8::detail::bigint>::format(const fmt::v8::detail::bigint&, fmt::v8::format_context&)::<lambda()>::FMT_COMPILE_STRING; typename std::enable_if<fmt::v8::is_compile_string<S>::value, int>::type <anonymous> = 0]’:
../../fmt/include/fmt/core.h:2848:41:   required from ‘fmt::v8::basic_format_string<Char, Args>::basic_format_string(const S&) [with S = fmt::v8::formatter<fmt::v8::detail::bigint>::format(const fmt::v8::detail::bigint&, fmt::v8::format_context&)::<lambda()>::FMT_COMPILE_STRING; typename std::enable_if<std::is_convertible<const S&, fmt::v8::basic_string_view<Char> >::value, int>::type <anonymous> = 0; Char = char; Args = {unsigned int&}]’
../../fmt/include/fmt/format-inl.h:2514:55:   required from here
../../fmt/include/fmt/core.h:2729:33:   in ‘constexpr’ expansion of ‘fmt::v8::detail::parse_format_string<true, char, fmt::v8::detail::format_string_checker<char, fmt::v8::detail::error_handler, unsigned int> >(s, fmt::v8::detail::format_string_checker<char, fmt::v8::detail::error_handler, unsigned int>(s, (fmt::v8::detail::error_handler(), fmt::v8::detail::error_handler())))’
../../fmt/include/fmt/core.h:2389:11: error: ‘__builtin___sanitizer_ptr_sub((((const char*)"{:x}") + 4), ((const char*)"{:x}"))’ is not a constant expression
../../fmt/include/fmt/core.h: In instantiation of ‘void fmt::v8::detail::check_format_string(S) [with <template-parameter-1-1> = {unsigned int&}; S = fmt::v8::formatter<fmt::v8::detail::bigint>::format(const fmt::v8::detail::bigint&, fmt::v8::format_context&)::<lambda()>::FMT_COMPILE_STRING; typename std::enable_if<fmt::v8::is_compile_string<S>::value, int>::type <anonymous> = 0]’:
../../fmt/include/fmt/core.h:2848:41:   required from ‘fmt::v8::basic_format_string<Char, Args>::basic_format_string(const S&) [with S = fmt::v8::formatter<fmt::v8::detail::bigint>::format(const fmt::v8::detail::bigint&, fmt::v8::format_context&)::<lambda()>::FMT_COMPILE_STRING; typename std::enable_if<std::is_convertible<const S&, fmt::v8::basic_string_view<Char> >::value, int>::type <anonymous> = 0; Char = char; Args = {unsigned int&}]’
../../fmt/include/fmt/format-inl.h:2518:55:   required from here
../../fmt/include/fmt/core.h:2729:33:   in ‘constexpr’ expansion of ‘fmt::v8::detail::parse_format_string<true, char, fmt::v8::detail::format_string_checker<char, fmt::v8::detail::error_handler, unsigned int> >(s, fmt::v8::detail::format_string_checker<char, fmt::v8::detail::error_handler, unsigned int>(s, (fmt::v8::detail::error_handler(), fmt::v8::detail::error_handler())))’
../../fmt/include/fmt/core.h:2389:11: error: ‘__builtin___sanitizer_ptr_sub((((const char*)"{:08x}") + 6), ((const char*)"{:08x}"))’ is not a constant expression
../../fmt/include/fmt/core.h: In instantiation of ‘void fmt::v8::detail::check_format_string(S) [with <template-parameter-1-1> = {int}; S = fmt::v8::formatter<fmt::v8::detail::bigint>::format(const fmt::v8::detail::bigint&, fmt::v8::format_context&)::<lambda()>::FMT_COMPILE_STRING; typename std::enable_if<fmt::v8::is_compile_string<S>::value, int>::type <anonymous> = 0]’:
../../fmt/include/fmt/core.h:2848:41:   required from ‘fmt::v8::basic_format_string<Char, Args>::basic_format_string(const S&) [with S = fmt::v8::formatter<fmt::v8::detail::bigint>::format(const fmt::v8::detail::bigint&, fmt::v8::format_context&)::<lambda()>::FMT_COMPILE_STRING; typename std::enable_if<std::is_convertible<const S&, fmt::v8::basic_string_view<Char> >::value, int>::type <anonymous> = 0; Char = char; Args = {int}]’
../../fmt/include/fmt/format-inl.h:2522:58:   required from here
../../fmt/include/fmt/core.h:2729:33:   in ‘constexpr’ expansion of ‘fmt::v8::detail::parse_format_string<true, char, fmt::v8::detail::format_string_checker<char, fmt::v8::detail::error_handler, int> >(s, fmt::v8::detail::format_string_checker<char, fmt::v8::detail::error_handler, int>(s, (fmt::v8::detail::error_handler(), fmt::v8::detail::error_handler())))’
../../fmt/include/fmt/core.h:2389:11: error: ‘__builtin___sanitizer_ptr_sub((((const char*)"p{}") + 3), ((const char*)"p{}"))’ is not a constant expression

**Comment by vitaut** [comment] 2021-07-20 13:33
Thanks for reporting. We don't document such things but the issue itself is discoverable and points to the root cause which is good. Closing since this is a bug in gcc.

**Closed by vitaut** 2021-07-20 13:33 UTC
