### ISSUE TITLE
got warning in fmt 8.1.0 [-Werror=extra]

### ISSUE THREAD

**Issue by ItayBar03** [fmtlib/fmt#2697] opened 2022-01-04 09:06 UTC
fmt-src/include/fmt/format.h:539:27: error: enumeral and non-enumeral type in conditional expression [-Werror=extra]
I use "treat warnings as error" so I can't use this version

**Comment by vitaut** [comment] 2022-01-05 01:27
What compiler version do you use?

**Comment by ItayBar03** [comment] 2022-01-05 08:17
in my project I use two compilers for two chips, xtensa-esp32s2-elf-gcc works fine,  and the riscv32-esp-elf-gcc is the problematic

**Comment by phprus** [comment] 2022-01-05 08:31
@vitaut I guess the problem is in the type of ``invalid_code_point``.
Maybe change type of ``invalid_code_point`` from ``enum`` to ``constexpr uint32_t``?

**Comment by vitaut** [comment] 2022-01-05 21:20
Should be fixed in https://github.com/fmtlib/fmt/commit/dbbd711f4635838290a10b1b3d8d378937a8741b.

**Closed by vitaut** 2022-01-05 21:20 UTC
