### ISSUE TITLE
How to handle errors in custom formatter `parse` method (doc bug)?

### ISSUE THREAD

**Issue by KubaO** [fmtlib/fmt#3522] opened 2023-07-04 23:05 UTC
The documentation example implies that there's `format_parse_context::on_error` method. But there doesn't seem to be so the below does not compile:

```
  constexpr auto parse(format_parse_context& ctx) -> format_parse_context::iterator {
    /* ... */
    if (it != end && *it != '}') ctx.on_error("invalid format");
    /* ... */
  }
```

**Comment by vitaut** [comment] 2023-07-05 02:11
Duplicate of #3458.

**Closed by vitaut** 2023-07-05 02:11 UTC
