### ISSUE TITLE
linker error with recent pull

### ISSUE THREAD

**Issue by VictorEijkhout** [fmtlib/fmt#2967] opened 2022-07-05 17:25 UTC
```
Undefined symbols for architecture x86_64:
  "fmt::v9::vformat(fmt::v9::basic_string_view<char>, fmt::v9::basic_format_args<fmt::v9::basic_format_context<fmt::v9::appender, char> >)", referenced from:
      _main in fmtlib.o
```

Looks like I'm missing something on the link line, but htere is only `libfmt.a`

**Comment by vitaut** [comment] 2022-07-05 17:41
Please provide a repro including build commands.

**Comment by VictorEijkhout** [comment] 2022-07-05 17:41
This error is preceeded by two warnings:
```
ld: warning: object file (/Users/eijkhout/Installation/fmtlib/installation-git-macbookair-clang/lib/libfmt.a(format.cc.o)) was built for newer macOS version (11.6) than being linked (11.0)
ld: warning: could not create compact unwind for __ZNK3fmt2v96detail14digit_groupingIcE5applyINS0_8appenderEcEET_S6_NS0_17basic_string_viewIT0_EE: stack subq instruction is too different from dwarf stack size
```
the first is something I'm getting all over with Mac OS Big Sur, and it doesn't seen to be serious. The second.....

**Comment by VictorEijkhout** [comment] 2022-07-05 17:52
https://github.com/VictorEijkhout/fmtlink

**Comment by vitaut** [comment] 2022-07-05 18:04
Closing as not reproducible. Please make sure that you don't have another fmt library in the library search path.

**Closed by vitaut** 2022-07-05 18:04 UTC

**Comment by weirdo-neutrino** [comment] 2022-09-01 18:04
Same problem.

```bash
/usr/bin/ld: /tmp/try-4b4491.o: in function `main':
try.cpp:(.text+0x127): undefined reference to `fmt::v9::vformat(fmt::v9::basic_string_view<char>, fmt::v9::basic_format_args<fmt::v9::basic_format_context<fmt::v9::appender, char> >)'
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
```

Here is code that do not link:

```cpp
#include <fmt/core.h>
#include <iostream>

int main()
{
    std::cout << fmt::format("{}", 1) << '\n';
}
```

```cpp
#include <fmt/core.h>
#include <iostream>

int main()
{
    std::cout << fmt::vformat(fmt::detail::to_string_view("{}"), fmt::make_format_args<fmt::buffer_context<char>>(1)) << '\n';
}
```

Instead here is code that do link:

```cpp
#include <fmt/core.h>
#include <iostream>
#include <fmt/format.h>

int main()
{
    fmt::basic_memory_buffer<char> buffer;
    auto format_str = fmt::detail::to_string_view("{}");
    auto args = fmt::make_format_args<fmt::buffer_context<char>>(1);
    fmt::detail::vformat_to(buffer, format_str, args);
    std::cout << fmt::to_string(buffer) << '\n';
}
```

```cpp
#include <fmt/core.h>
#include <iostream>
#include <fmt/format.h>

template <typename Char>
auto myformat(fmt::basic_string_view<Char> format_str,
    fmt::basic_format_args<fmt::buffer_context<fmt::type_identity_t<Char>>> args)
    -> std::basic_string<Char>
{
    fmt::basic_memory_buffer<Char> buffer;
    fmt::detail::vformat_to(buffer, format_str, args);
    return fmt::to_string(buffer);
}

int main()
{
    std::cout << myformat(fmt::detail::to_string_view("{}"), fmt::make_format_args<fmt::buffer_context<char>>(1)) << '\n';
}
```

The root problem seems to do with [FMT_ENABLE_IF](https://github.com/fmtlib/fmt/tree/master/include/fmt/core.h#L333), as the code linked when I copied `vformat` function and removed FMT_ENABLE_IF from it.

**Comment by weirdo-neutrino** [comment] 2022-09-15 16:23
For history: fec5515c55f85143077806bf01650c23b08d3751 fixed it

**Comment by mhx** [comment] 2024-05-17 17:20
I ran into the same issue and it looks like a bug in Clang: https://github.com/llvm/llvm-project/issues/62765#issuecomment-2118040421

Also, it looks like this is no longer an issue with fmt v10.

**Comment by alexpanter** [comment] 2024-06-20 11:43
> I ran into the same issue and it looks like a bug in Clang: [llvm/llvm-project#62765 (comment)](https://github.com/llvm/llvm-project/issues/62765#issuecomment-2118040421)
> 
> Also, it looks like this is no longer an issue with fmt v10.

I have a repository which has been compiling fine on Ubuntu.
Just switched to Windows today, and I get this exact linking error with fmt::v9

So I updated my spdlog submodule which depended on fmt9, now it depends on fmt::10.
And I still get the exact same error:
```
1>vtek_fileio.obj: Error LNK2019 : unresolved external symbol "public: __cdecl fmt::v10::detail::value<class fmt::v10::basic_format_context<class fmt::v10::appender,char> >::value<class fmt::v10::basic_format_context<class fmt::v10::appender,char> >(struct fmt::v10::detail::unformattable_char)" (??0?$value@V?$basic_format_context@Vappender@v10@fmt@@D@v10@fmt@@@detail@v10@fmt@@QEAA@Uunformattable_char@123@@Z) referenced in function "class fmt::v10::detail::value<class fmt::v10::basic_format_context<class fmt::v10::appender,char> > __cdecl fmt::v10::detail::make_arg<1,class fmt::v10::basic_format_context<class fmt::v10::appender,char>,wchar_t const ,0>(wchar_t const &)" (??$make_arg@$00V?$basic_format_context@Vappender@v10@fmt@@D@v10@fmt@@$$CB_W$0A@@detail@v10@fmt@@YA?AV?$value@V?$basic_format_context@Vappender@v10@fmt@@D@v10@fmt@@@012@AEB_W@Z)
1>vtek_fileio.obj: Error LNK2019 : unresolved external symbol "public: __cdecl fmt::v10::detail::value<class fmt::v10::basic_format_context<class fmt::v10::appender,char> >::value<class fmt::v10::basic_format_context<class fmt::v10::appender,char> >(struct fmt::v10::detail::unformattable_pointer)" (??0?$value@V?$basic_format_context@Vappender@v10@fmt@@D@v10@fmt@@@detail@v10@fmt@@QEAA@Uunformattable_pointer@123@@Z) referenced in function "class fmt::v10::detail::value<class fmt::v10::basic_format_context<class fmt::v10::appender,char> > __cdecl fmt::v10::detail::make_arg<1,class fmt::v10::basic_format_context<class fmt::v10::appender,char>,wchar_t const * const,0>(wchar_t const * const &)" (??$make_arg@$00V?$basic_format_context@Vappender@v10@fmt@@D@v10@fmt@@QEB_W$0A@@detail@v10@fmt@@YA?AV?$value@V?$basic_format_context@Vappender@v10@fmt@@D@v10@fmt@@@012@AEBQEB_W@Z)
1>vtekd.dll: Error LNK1120 fatal: 2 unresolved externals
1>------- Finished building project: vtek. Succeeded: False. Errors: 3. Warnings: 0
```

I have no idea what all this means. Just that it was fine on Linux, and it's definitely not fine on Windows - neither in fmt9 or fmt10.

For reference, my project is created with cmake, and fmt is only indirectly used through spdlog.
