### ISSUE TITLE
10.0.0: basic_format_parse_context lost on_error API

### ISSUE THREAD

**Issue by Dani-Hub** [fmtlib/fmt#3538] opened 2023-07-18 15:36 UTC
Starting with fmtlib 10, the following code does no longer compile anymore:

https://godbolt.org/z/W8oT9WG1q

This code is the verbatim example from

https://fmt.dev/10.0.0/api.html#formatting-user-defined-types

which uses the `on_error` member function from `basic_format_parse_context` to handle errors. Similar code which is part of our company's code base broke due to that change.

Initially I assumed this change was intentional (and that the documented API example should be adjusted), but since the previous `on_error` delegated to internal API (Such as `throw_format_error`) it is unclear how use code should correctly handle the error without referring to internal API.

**Comment by vitaut** [comment] 2023-07-18 20:52
Duplicate of #3458.

**Closed by vitaut** 2023-07-18 20:52 UTC
