### ISSUE TITLE
Cannot use ostream support on fmt 9.x and 10.x

### ISSUE THREAD

**Issue by ahoarau** [fmtlib/fmt#3922] opened 2024-04-06 07:45 UTC
Hello !
I'm having compile issues on fmt 9.x and 10.x with the `ostream` extension.
Same on `msvc` (latest) and `gcc 13.2` : https://godbolt.org/z/8oejx8Yfn
Thanks for the help !

```cpp
#include <fmt/ostream.h>

struct A{};

std::ostream& operator<<(std::ostream& os, const A& a)
{
    os << "Hello !";
    return os;
}

int main()
{
    fmt::print("{}", A{});
}
```

## 7.x =>  ✅
![image](https://github.com/fmtlib/fmt/assets/703240/d34cce9a-76a7-4d39-a394-a00a32a9b63a)
## 8.x =>   ✅ 
![image](https://github.com/fmtlib/fmt/assets/703240/350f67db-6cb4-4cff-8d0f-8cd22c05fd4e)
## 9.x => ❌
![image](https://github.com/fmtlib/fmt/assets/703240/d335d389-1a67-4350-8050-5aec8b0ee213)
## 10.x => ❌
![image](https://github.com/fmtlib/fmt/assets/703240/d8ecad22-f433-46b9-b7c7-630ca0cbd876)

**Comment by vitaut** [comment] 2024-04-06 18:42
Duplicate of #3318.

**Closed by vitaut** 2024-04-06 18:42 UTC
