### ISSUE TITLE
Error in producing the output file using API fmt::output_file

### ISSUE THREAD

**Issue by 07anhad** [fmtlib/fmt#3511] opened 2023-06-27 04:28 UTC
Hi @vitaut while using fmt::output_file

```cpp
#include "fmt/os.h" 
auto out = fmt::output_file(ouputfile.c_str(),fmt::buffer_size=4096);
if(fp != NULL) {
out.print("anhad {}","debug");
if(type == "i" || type == "j" || type == "k" || type == "all")
 out.print("\nabc\n\xyz = {}\n", function_1().c_str());
```

The file is being created, but no value is being dumped in the file.
What might have been the problem?

I even tried by making a `.txt` file like

```cpp
auto out = fmt::output_file("test1.txt",fmt::buffer_size=4096);
```

still the file was being produced but not data is being generated.

Initially in `fmt::V5` I was using `buffered_file` api. and `fmt::fprintf` insted of system fprintf.
Things worked fine then.

```cpp
file = new fmt::buffered_file(ouputfile.c_str(),"w");
auto fp(file->get());
if(fp != NULL) {
    if(type == "i" || type == "j" || type == "k" || type == "all")
      fmt::fprintf(fp,"\n abc\n\nxyz = %s\n", function_1.c_str());
 
```
But after coming across your article 

[https://www.zverovich.net/2020/08/04/optimal-file-buffer-size.html](url)

I want to implement the `fmt::output_file` API

PS: Is it possible to achieve the same results with `fmt::buffered_file` api in V::10?

**Comment by vitaut** [comment] 2023-06-27 14:41
I was not able to repro the issue but I see a few issues in your code, e.g. `fp` is not defined, which might explain why the branch that writes to a file is not taken. Closing but if the issue is still there after you fixed bugs in your code please provide a godbolt repro.

**Closed by vitaut** 2023-06-27 14:41 UTC

**Comment by 07anhad** [comment] 2023-06-28 09:45
Hi @vitaut,

Is there a direct method to check if the output file is successfully opened?

**Comment by vitaut** [comment] 2023-06-28 13:24
If the file wasn't open `output_file` would throw an exception.

**Comment by 07anhad** [comment] 2023-06-28 17:59
So using `GDB` the program breaks when it reaches `if(fp!=NULL)`.  Its printing the `debug message` before and after this check. 

I know before in the program fp was used and null checks are done for `fp`, but in output_file API of fmt, it does not accept file pointer as the first argument.

If I try a null check with out its giving the following error: 

`path/to/file.cpp:55:9:  error: no match for 'operator==' (operand types are 'fmt::v10::ostream' and 'long int')
   if(out==NULL){
`

**What can be the fix for** 

1) Instead of file pointer `fp` to use the `out` to check for NULL.

**2) to print the values of these statements in output_file `out`

The issue might be a very minor one, but I can't seem to figure this out.

```cpp
FILE* func (arg1,arg2,arg3)
{
  FILE *fp = NULL;
  //try {
  fmt::ostream out = fmt::output_file(file.c_str(),fmt::buffer_size=4096);
  out.print("DEBUG {}","MESSAGE1");
 // } catch(...)

  if(fp==NULL){
   *something*
    }
  
  if(fp != NULL){
    if(type == "i" || type == "j" || type == "k" ||)
   out.print("\n abc = {}\n", xyz);
    else
      out.print("\n{} cde \n\n", type.c_str());
    out.print("lmn          = {}\n",uvw);
}

  out.print("DEBUG {}","MESSAGE2");

return fp;
}
```

I am unable to povide a godbolt repro, as there is some problem in sharing the link, but for now I have provided the code below.

**Comment by vitaut** [comment] 2023-06-28 18:18
StackOverflow (https://stackoverflow.com/questions/tagged/fmt) might be a better place to ask questions like this. This issue tracker is mainly for reporting bugs in {fmt}.

**Comment by 07anhad** [comment] 2023-06-28 18:51
Okay, thanks
