### ISSUE TITLE
Enable constexpr support on format 

### ISSUE THREAD

**Issue by bebuch** [fmtlib/fmt#3403] opened 2023-04-24 21:40 UTC
I just tried calling `fmt::format` in a constexpr context (`static_assert`) and found that it doesn't work. Since C++20 has `constexpr` support for `std::string`, it should also be possible to add `constexpr` support to `fmt::format`.

```cpp
#include <string_view>
#include <fmt/core.h>

using namespace std::literals;
static_assert(fmt::format("{}", 5) == "5"sv);
```

- https://godbolt.org/z/q48YxY7sE

Is there anything against this?

**Comment by vitaut** [comment] 2023-04-25 15:04
It can't be done in the core API but making the `format` overload in `fmt/compile.h` conditionally `constexpr` should be doable:

https://github.com/fmtlib/fmt/blob/62ff4e1dbd6651a3ee9b78657c481b48b3c528fa/include/fmt/compile.h#L521-L524

A PR is welcome.

**Comment by alexezeder** [comment] 2023-04-25 22:48
IIRC, the problem is actually that you cannot simply create `std::string` and make it escape a constant-evaluated context, since all allocated memory with `new` operator should be deallocated. This is according to [P0784 - More constexpr containers](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p0784r7.html#:~:text=%E2%80%94%20a%20new%2Dexpression%20(7.6.2.4)%2C%20unless%20the%20selected%20allocation%20function%20is%20a%20replaceable%20global%20allocation%20function%20(16.6.2.1%2C%2016.6.2.2)%20and%20the%20allocated%20storage%20is%20deallocated%20within%20the%20evaluation%20of%20e%3B).

**Comment by bebuch** [comment] 2023-04-25 22:56
I would be a problem if you mark the function consteval, so it is always evaluated at compile time. With constexpr it's only compile time evaluated, if the hole expression is in a compile time context. I'm quiet sure this should never make problems ;-)

**Comment by alexezeder** [comment] 2023-04-25 23:15
Here is the problem example that I was referring to - https://godbolt.org/z/Y4WbPYzbx. Thus, `format()` cannot be called in a constant-evaluated context here because the result is escaping constant-evaluated context apparently. But with `static_assert` it works because entire usage is inside a constant-evaluated context, nothing escapes.

**Comment by bebuch** [comment] 2023-04-26 00:07
If I'm not wrong, you actually can use it in this context. You just can't use the variable abc in a non constexpr context. But that's the case for any constexpr std::string so it's nothing special about creating ît by format. Also note that this would never break backwards comparably, because it's currently not possible to initialize a constexpr variable from format.

The constexpr should only enable new use cases without breaking any existing code.

There are cases (like constinit variables) where you can't use it because of the compile time / run time restriction, but this shouldn't be a problem because they don't work at the moment as well.

**Comment by vitaut** [comment] 2023-06-17 07:35
Closing as it is possible to achieve the same effect via existing APIs (`format_to`) but a PR to add optional `constexpr` support to `format` would be welcome.

**Closed by vitaut** 2023-06-17 07:35 UTC
Labels: enhancement

**Comment by bebuch** [comment] 2023-06-19 20:20
I just want to note that the compiler features *`constexpr` cast from `void*`* [P2738](https://wg21.link/P2738) and *User-generated `static_assert` messages* [P2741](https://wg21.link/P2741) have just been voted into C++26. Both refer explicitly to `constexpr` `std::format`. 🎉

`fmt/std::format` in `static_assert` error messages would be dream! 😁

**Comment by cor3ntin** [comment] 2023-07-23 11:17
Clang (trunk, 17) supports both [P2738](https://wg21.link/P2738) and  [P2741](https://wg21.link/P2741).

Better constexpr support in fmt would indeed be excellent. Right now it's a bit cumbersome https://compiler-explorer.com/z/rK7sdPj9j 

```cpp
constexpr auto msg() {
    char c[100] = {};
    fmt::format_to(c, FMT_COMPILE("The answer is {}."), 42);
    return std::string(c);
};
static_assert(false, msg());```

**Comment by mpusz** [comment] 2025-03-20 19:28
This might be useful for some of you:

```cpp
consteval std::string constexpr_format(auto fmt, auto&&... args)
{
  std::string text;
  fmt::format_to(std::back_inserter(text), fmt, std::forward<decltype(args)>(args)...);
  return text;
};
```

It is a pity that `fmt::format` does not do it by default.

**Comment by vitaut** [comment] 2025-09-07 15:56
This is supported via the compile-time API as of #4456 and only requires C++20.
