### ISSUE TITLE
Chrono fmt::format in UTC

### ISSUE THREAD

**Issue by Kaaml** [fmtlib/fmt#3466] opened 2023-05-29 19:52 UTC
Hi, 

Default behaviour of fmt is to use locale and format time using local timezone. How should be used fmt to always print time in UTC instead of local time zone?

**Comment by vitaut** [comment] 2023-05-29 22:12
Looks like a duplicate of #3199. If this is not the case please provide more details and a godbolt repro.

**Closed by vitaut** 2023-05-29 22:12 UTC
