### ISSUE TITLE
Bug: fmt::print(...) infinite recursion when using std::filesystem::path and fmt/ranges.h header is included

### ISSUE THREAD

**Issue by odygrd** [fmtlib/fmt#1268] opened 2019-08-18 22:46 UTC
Executing the following code will enter an infinite recursion and the program will crash

template <typename... Args>
auto capture(const Args&... args) {
  return std::make_tuple(args...);
}

auto print_message = [](const auto&... args) {
  fmt::print(args...);
};

int main()
{
  std::filesystem::path ph {"test_path"};
  
  auto args = capture("{}", ph);
  
  std::apply(print_message, args);
}

**Comment by vitaut** [comment] 2019-08-19 00:23
I wasn't able to make your example compile: https://godbolt.org/z/FKJcEH. Please provide more examples including the compiler version and {fmt} library version.

**Comment by odygrd** [comment] 2019-08-19 02:02
I see it doesn't compile. 
I am using gcc 9.1 and the libfmt version was very recent from master last updated about ~15/20 days ago but I don't have the exact commit hash. 
Maybe you've changed something within that period

**Comment by odygrd** [comment] 2019-08-19 02:45
I made it compile on gotbolt and also locally

https://godbolt.org/z/g1c6Q-

When fmt/ranges.h is not included the program runs fine.
If I also include rmt/ranges.h it will crash
I get ~94000 lines of stack so it is hard to copy paste here but it looks like this 

![image001](https://user-images.githubusercontent.com/7397786/63235938-b5291580-c233-11e9-99b0-99969bcbeb00.png)

**Comment by vitaut** [comment] 2019-08-21 17:12
The problem is that `std::filesystem::path` looks like a range because it has `begin()` and `end()` which enables `formatter` specialization for ranges. However the latter should really be disabled because implicit conversion of a path to `std::string` results in a dangling reference.

**Comment by vitaut** [comment] 2019-08-21 20:02
Fixed in https://github.com/fmtlib/fmt/commit/b2d4ca154633d44765b87aac580ea59d8202dcd5. Thanks for reporting!

**Closed by vitaut** 2019-08-21 20:02 UTC
