### ISSUE TITLE
user-defined types with overloaded operator<< don't work after 7.0.3

### ISSUE THREAD

**Issue by odygrd** [fmtlib/fmt#2014] opened 2020-11-12 09:47 UTC
It looks like that user defined types with an overloaded `operator<<`, no longer work when they are used in a container.

Broken example with fmt 7.1.x

https://godbolt.org/z/z1jn66

the same example compiles fine with fmt 7.0.x

https://godbolt.org/z/Wqbjsf

**Comment by MikeGitb** [comment] 2020-11-12 12:28
Have the same problem with user defined types that have an implicit conversion to `std::string_view`:

https://godbolt.org/z/EWfo1h

    #include <fmt/core.h>
    #include <fmt/format.h>
    #include <fmt/ranges.h>

    #include <string_view>

    struct Foo {
        operator std::string_view() const { return "Hello";}
    };

    int main() {
        std::vector<Foo> v(5);
        fmt::print("{}", v);
    }

**Comment by vitaut** [comment] 2020-11-19 15:27
This is caused by https://github.com/fmtlib/fmt/commit/2f7e08856b6eaa65a4da44c142422e71229c4a20. We should probably add support for the `fallback_formatter` there.

**Comment by odygrd** [comment] 2020-11-21 11:31
I think this should be fixed as part of the next release, it has broken backward compatibility with the previous fmt versions

**Comment by vitaut** [comment] 2020-11-21 17:20
Yes, that's the plan.

**Comment by vitaut** [comment] 2020-11-22 00:46
Fixed in https://github.com/fmtlib/fmt/commit/a036cc97b7e547ad93d031abb3b66c7c4ab70662.

**Closed by vitaut** 2020-11-22 00:46 UTC
