### ISSUE TITLE
assert-test fails in 8.1.0

### ISSUE THREAD

**Issue by candrews** [fmtlib/fmt#2690] opened 2022-01-03 19:37 UTC
In fmt 8.1.0, I'm seeing the `assert-test` failing. Here's the output:
```
2/19 Testing: assert-test
2/19 Test: assert-test
Command: "/var/tmp/portage/dev-libs/libfmt-8.1.0/work/libfmt-8.1.0_build-abi_x86_64.amd64/bin/assert-test"
Directory: /var/tmp/portage/dev-libs/libfmt-8.1.0/work/libfmt-8.1.0_build-abi_x86_64.amd64/test
"assert-test" start time: Jan 03 12:24 EST
Output:
----------------------------------------------------------
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from assert_test
[ RUN      ] assert_test.fail
/var/tmp/portage/dev-libs/libfmt-8.1.0/work/fmt-8.1.0/test/assert-test.cc:17: Failure
Death test: ((false) ? (void)0 : ::fmt::detail::assert_fail("/var/tmp/portage/dev-libs/libfmt-8.1.0/work/fmt-8.1.0/test/assert-test.cc", 17, ("don't panic!")))
    Result: died but not with expected error.
  Expected: contains regular expression "don't panic!"
Actual msg:
[  DEATH   ] 
[  FAILED  ] assert_test.fail (73 ms)
[ RUN      ] assert_test.dangling_else
[       OK ] assert_test.dangling_else (0 ms)
[----------] 2 tests from assert_test (73 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test suite ran. (73 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] assert_test.fail

 1 FAILED TEST
<end of output>
Test time =   0.08 sec
----------------------------------------------------------
Test Failed.
"assert-test" end time: Jan 03 12:24 EST
"assert-test" time elapsed: 00:00:00
----------------------------------------------------------
```

And here's [LastTest.log](https://github.com/fmtlib/fmt/files/7803710/LastTest.log)

**Comment by vitaut** [comment] 2022-01-03 20:04
Please post repro details, particularly build flags and compiler version.

**Comment by candrews** [comment] 2022-01-03 20:14
gcc (Gentoo 11.2.1_p20211127 p0) 11.2.1 20211127
CFLAGS: `-O2 -march=native -pipe -fuse-linker-plugin -flto -Wl,-flto -ftree-vectorize -falign-functions=32 -fgraphite-identity -floop-nest-optimize -fno-common`
LDFLAGS: `-Wl,-O1 -Wl,--as-needed -flto -Wl,--hash-style=gnu`


Here's the build log which has all that information:
[build.log](https://github.com/fmtlib/fmt/files/7803841/build.log)

**Comment by vitaut** [comment] 2022-01-05 01:17
Hmm, I wasn't able to repro this in a similar environment. Does adding `fflush(stderr)` before this line help 

https://github.com/fmtlib/fmt/blob/214cf13f17c7177912cc8f9b6c070c4b3a282c36/include/fmt/format-inl.h#L40

?

**Comment by candrews** [comment] 2022-01-07 15:24
> `fflush(stderr)`

I gave that a shot and it made no different; the test still fails in the same way.

**Comment by candrews** [comment] 2022-01-07 16:05
It's not just me... Gentoo's CI system also sees this test failure: https://bugs.gentoo.org/show_bug.cgi?id=830737

**Comment by vitaut** [comment] 2022-01-07 18:32
Interesting. I don't have an explanation why the assertion's message is not printed and debugging help from someone who can repro it might be needed.

**Comment by candrews** [comment] 2022-01-07 18:49
I can reproduce it - if you tell me what to do, I'm happy to do it and relay results.

**Comment by vitaut** [comment] 2022-01-07 19:00
Thanks! Could you check what is the stderr output of the following program:

```c++
#include <fmt/core.h>

int main() {
  FMT_ASSERT(false, "don't panic!");
}
```
?

This will narrow down if the problem is in `FMT_ASSERT` or gtest.

**Comment by candrews** [comment] 2022-01-07 21:25
```
$ g++ test.cpp -lfmt -o test && ./test
test.cpp:4: assertion failed: don't panic!terminate called without an active exception
Aborted (core dumped)
```

**Comment by candrews** [comment] 2022-01-15 17:30
Is there any further testing I can perform or information I can provide to assist with this issue?

**Comment by vitaut** [comment] 2022-01-17 20:13
Could you provide a preprocessed file that reproduces the issue?

**Comment by vitaut** [comment] 2022-01-20 20:29
Also is there any difference between running the test directly (`bin/assert-test`) vs via ctest?

**Comment by vitaut** [comment] 2022-01-21 14:31
I was not able to repro the issue on Gentoo with gcc 11.2 with the default configuration

```
$ git clone https://github.com/fmtlib/fmt.git
$ cd fmt
$ cmake .
$ make -j10
$ bin/assert-test
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from assert_test
[ RUN      ] assert_test.fail
[       OK ] assert_test.fail (0 ms)
[ RUN      ] assert_test.dangling_else
[       OK ] assert_test.dangling_else (0 ms)
[----------] 2 tests from assert_test (0 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test suite ran. (0 ms total)
[  PASSED  ] 2 tests.
```

It could be something specific to your build configuration or the way tests are invoked. Closing for now but feel free to reopen with repro details.

**Closed by vitaut** 2022-01-21 14:31 UTC

**Comment by candrews** [comment] 2022-01-22 16:15
The Gentoo CI system can reproduce it and that runs a very vanilla configuration. If it can see it, this is definitely not a "only on my system" kind of problem.

**Comment by vitaut** [comment] 2022-01-22 16:23
Sure but this needs to either be turned into something reproducible for us to be able to debug or someone with an access to the CI system will have to investigate why the failure happens there.
