### ISSUE TITLE
.so not built on RHEL/CentOS 7

### ISSUE THREAD

**Issue by daveisfera** [fmtlib/fmt#370] opened 2016-08-13 04:16 UTC
fmt 3.0 builds without issue on Fedora 23 but when I try building on RHEL/CentOS 7, CMAKE_INSTALL_PREFIX is set to /usr/local instead of /usr and the .so is not generated. Even if I manually set CMAKE_INSTALL_PREFIX, the .so is still not generated.
What can I do to help diagnose the cause of this issue?
Thanks,
Dave

**Comment by vitaut** [comment] 2016-08-13 16:10
Do you run CMake with `-DBUILD_SHARED_LIBS=True`? Also could you post the full output of running

```
cmake -DBUILD_SHARED_LIBS=True -DCMAKE_INSTALL_PREFIX=/usr/local .
make
make doc
sudo make install
```

**Comment by vitaut** [comment] 2016-08-19 23:28
I was not able to reproduce it on CentOS 7:

```
-- Installing: /usr/local/lib/libfmt.so.3.1.0
-- Installing: /usr/local/lib/libfmt.so.3
-- Installing: /usr/local/lib/libfmt.so
```
so I'm closing the issue. Feel free to reopen providing additional info.

**Closed by vitaut** 2016-08-19 23:28 UTC

**Comment by daveisfera** [comment] 2016-08-23 03:21
I can't reproduce the issue anymore, so I'm not sure what the problem was. Sorry for the noise.
