### ISSUE TITLE
Multiple warnings under MSVC 2019

### ISSUE THREAD

**Issue by Sunslash** [fmtlib/fmt#1253] opened 2019-07-27 15:52 UTC
Hello,

I have imported this nice library into a project compiled using the latest MSVC. From what I understand multiple check have been added recently by Microsoft, resulting in a laundry list of warnings: 

```
C26451	Arithmetic overflow: Using operator '-' on a 4 byte value and then casting the result to a 8 byte value. Cast the value to the wider type before calling operator '-' to avoid overflow (io.2).	fmt\format-inl.h	422	

C26451	Arithmetic overflow: Using operator '+' on a 4 byte value and then casting the result to a 8 byte value. Cast the value to the wider type before calling operator '+' to avoid overflow (io.2).	fmt\format-inl.h	460	

C26451	Arithmetic overflow: Using operator '-' on a 4 byte value and then casting the result to a 8 byte value. Cast the value to the wider type before calling operator '-' to avoid overflow (io.2).	fmt\format-inl.h	460	

C26451	Arithmetic overflow: Using operator '+' on a 4 byte value and then casting the result to a 8 byte value. Cast the value to the wider type before calling operator '+' to avoid overflow (io.2).	fmt\format-inl.h	824	

C26451	Arithmetic overflow: Using operator '+' on a 4 byte value and then casting the result to a 8 byte value. Cast the value to the wider type before calling operator '+' to avoid overflow (io.2).	fmt\format-inl.h	852	

C26451	Arithmetic overflow: Using operator '+' on a 4 byte value and then casting the result to a 8 byte value. Cast the value to the wider type before calling operator '+' to avoid overflow (io.2).	fmt\format-inl.h	879	

C26495	Variable 'fmt::v5::internal::counting_iterator<char>::blackhole_' is uninitialized. Always initialize a member variable (type.6).	fmt\format.h	301	

C26451	Arithmetic overflow: Using operator '*' on a 4 byte value and then casting the result to a 8 byte value. Cast the value to the wider type before calling operator '*' to avoid overflow (io.2).	fmt\format.h	736	

C26451	Arithmetic overflow: Using operator '*' on a 4 byte value and then casting the result to a 8 byte value. Cast the value to the wider type before calling operator '*' to avoid overflow (io.2).	fmt\format.h	1002	

C26495	Variable 'fmt::v5::internal::basic_writer<fmt::v5::internal::buffer_range<char> >::int_writer<__int64,fmt::v5::basic_format_specs<char> >::prefix' is uninitialized. Always initialize a member variable (type.6).	fmt\format.h	1353	

C26495	Variable 'fmt::v5::internal::basic_writer<fmt::v5::internal::buffer_range<char> >::int_writer<char,fmt::v5::basic_format_specs<char> >::prefix' is uninitialized. Always initialize a member variable (type.6).	fmt\format.h	1353	

C26495	Variable 'fmt::v5::internal::basic_writer<fmt::v5::internal::buffer_range<char> >::int_writer<int,fmt::v5::basic_format_specs<char> >::prefix' is uninitialized. Always initialize a member variable (type.6).	fmt\format.h	1353	

C26495	Variable 'fmt::v5::internal::basic_writer<fmt::v5::internal::buffer_range<char> >::int_writer<unsigned __int64,fmt::v5::basic_format_specs<char> >::prefix' is uninitialized. Always initialize a member variable (type.6).	fmt\format.h	1353	

C26495	Variable 'fmt::v5::internal::basic_writer<fmt::v5::internal::buffer_range<char> >::int_writer<unsigned int,fmt::v5::basic_format_specs<char> >::prefix' is uninitialized. Always initialize a member variable (type.6).	fmt\format.h	1353	

C26451	Arithmetic overflow: Using operator '+' on a 4 byte value and then casting the result to a 8 byte value. Cast the value to the wider type before calling operator '+' to avoid overflow (io.2).	fmt\format.h	1477	

C26451	Arithmetic overflow: Using operator '+' on a 4 byte value and then casting the result to a 8 byte value. Cast the value to the wider type before calling operator '+' to avoid overflow (io.2).	fmt\format.h	1477	

C26451	Arithmetic overflow: Using operator '+' on a 4 byte value and then casting the result to a 8 byte value. Cast the value to the wider type before calling operator '+' to avoid overflow (io.2).	fmt\format.h	1568	

C26451	Arithmetic overflow: Using operator '+' on a 4 byte value and then casting the result to a 8 byte value. Cast the value to the wider type before calling operator '+' to avoid overflow (io.2).	fmt\format.h	1692	

C6387	'value' could be '0':  this does not adhere to the specification for the function 'std::char_traits<char>::length'. 	fmt\format.h	1746	

C26498	The function 'std::numeric_limits<int>::max' is constexpr, mark variable 'max_int' constexpr if compile-time evaluation is desired (con.5).	fmt\format.h	1855	

C26495	Variable 'fmt::v5::system_error::error_code_' is uninitialized. Always initialize a member variable (type.6).	fmt\format.h	2646	

```

Note that it compiles and runs without problem. I guess it's just MSVC being overly pedantic, but since we treat all warnings as errors it would be nice to remove them.

**Comment by mwinterb** [comment] 2019-07-29 02:18
Dupe of #1131. As a note, these particular warnings (as in 1131) are all Core Guidelines warnings, so clang-tidy would theoretically also report similar warnings. [[gsl::suppress()]] would allow for more targeted suppression in a mildly cross-tool way (since of course they don't agree https://github.com/microsoft/GSL/blob/6418b5f4de2204cd5a335b00d2f8754301b8b382/include/gsl/gsl_assert#L24).

**Comment by Sunslash** [comment] 2019-07-29 06:42
Ok sorry, I searched for the issue but somehow missed that ticket.
Most of the warning seem pretty easy to correct, I might do it down the line if we decide to use this lib for long term development.

**Comment by vitaut** [comment] 2019-08-11 14:03
These warnings are pure noise, but if anyone is interested in suppressing them, a PR is welcome.

**Closed by vitaut** 2019-08-11 14:03 UTC
