### ISSUE TITLE
adl/sfinae errors with format_to

### ISSUE THREAD

**Issue by nuoHep** [fmtlib/fmt#2603] opened 2021-11-18 13:54 UTC
Not sure if this is a "bug" in fmt or just a fallout of us using the same name.

We have a small helper to simplify formatting types using a single function. Unfortunately, we chose the "same" name - `format_to` (designed to be found through adl) as `fmt::format_to()`. It worked fine before 8.0, but with 8.0 it started clashing with the fmt one presumably because our detection machinery now picks up the fmt one by adl through the second argument. Or smth.

Long story short: https://godbolt.org/z/dPW6fjP8r
It works fine as-is. But as soon as you uncomment either `HEADER_ONLY` or `format.h` it starts erroring out. As far as I can see this is because `detail::is_output_iterator` is not sfinae friendly when presented with a `void*` because of the specialization of iterator traits for it. So it may actually be possible this works on some stls...

Anyway, we fixed it up by renaming our internal `format_to`, so it's not a problem. More like a heads up.

**Comment by vitaut** [comment] 2021-11-18 14:16
Closing as this doesn't look like a bug in {fmt}, just a wrong type passed to `fmt::format_to`.

**Closed by vitaut** 2021-11-18 14:16 UTC

**Comment by nuoHep** [comment] 2021-11-18 14:33
> Closing as this doesn't look like a bug in {fmt}, just a wrong type passed to `fmt::format_to`.

Umm, no? I guess I was not clear enough. The only place calling `fmt::format_to()` passes the proper arguments - `fmt::format_to( out, "{}", dummy_to_string( d ) );`.
The actual error happens in the `detail::has_format_to` trait which "calls" to an unqualified `format_to()` in the hopes to find it through adl.

If you look here https://godbolt.org/z/M961azWde (which gets an error) the "call" which fails is this:
```
void_t<decltype( format_to( std::declval<const T&>(), std::declval<::fmt::format_context::iterator>() ) )>`
```
which does un unqualified call.

**Comment by vitaut** [comment] 2021-11-18 14:43
The error message suggests that the unqualified call in question resolves to `fmt::format_to` (via ADL).

**Comment by nuoHep** [comment] 2021-11-18 15:24
Well, yes, it gets resolved to that here.

Looking at the backtrace it gets invoked somewhere inside {fmt} with `T = const void*`, so the call looks like `format_to(const void*, fmt::format_context::itarator)`. It gets resolved to `fmt::format_to` via ADL on the second argument (which is a bit surprising). And then fails in the enable_if on `fmt::format_to()` https://github.com/fmtlib/fmt/blob/c089f7d497bcce35a0fd6da0512f8585ed1cc002/include/fmt/core.h#L3098 which presumably should sfinae out invalid calls but fails for `OutputIt = void*` inside `std::iterator_traits`.

I dunno tbh. To me both resolving of unqualified `format_to(void*, fmt::format_context::iterator)` to `fmt::format_to` and then a failure to sfinae out `fmt::format_to` on `void*` seem surprising. But I will admit it's an edge case because of our use of the "same" name for this.

**Comment by vitaut** [comment] 2021-11-18 15:40
Formatting functions are not SFINAE-friendly by design because they report some errors as compile-time errors. You should probably use traits instead.

**Comment by nuoHep** [comment] 2021-11-18 16:41
I'm sorry, I don't follow. Which traits and for what?

I'm not trying to call a (n {fmt}) formatting function here.
I'm trying to use a custom trait to check if a type `T` has an adl discoverable function of a signature `format_to(const T&, fmt::format_context::iterator)` in an idiomatic fashion.

A simplified example
```cpp
#include "fmt/core.h"

namespace detail {
template <typename...> using void_t = void;
template <typename T, typename = void> struct has_format_to : std::false_type {};
template <typename T>
struct has_format_to<T,
  void_t<decltype( format_to( std::declval<const T&>(),
                              std::declval<::fmt::format_context::iterator>() ) ) > > : std::true_type {};
} // namespace detail

static_assert(detail::has_format_to<int>::value == false); // works
static_assert(detail::has_format_to<void*>::value == false); // doesn't work
```
fails in the same way: https://godbolt.org/z/K6fz9e6ja and **only** for pointers to void.

**Comment by vitaut** [comment] 2021-11-18 16:54
> Which traits and for what?

`is_formattable` trait for instance: https://github.com/fmtlib/fmt/blob/c089f7d497bcce35a0fd6da0512f8585ed1cc002/include/fmt/core.h#L1760 and whatever traits you need for other arguments.

Whether you want to call `fmt::format_to` or not it is being discovered via ADL because of `fmt::format_context::iterator` so it will expectedly fail for reasons explained earlier.

**Comment by nuoHep** [comment] 2021-11-18 17:49
> Whether you want to call `fmt::format_to` or not it is being discovered via ADL because of `fmt::format_context::iterator` so it will expectedly fail for reasons explained earlier.

I understand why it fails. But I assert that it is inconsistent. You do have an enable_if on it for *some reason* and it mostly works as one would expect apart from (const) pointers to void. I mean...
`fmt::format_to( int(0), ... );` does not compile because of the enable if
`fmt::format_to( static_cast<char*>(nullptr), ... );` compiles
`fmt::format_to( static_cast<double*>(nullptr), ... );` *also* compiles
`fmt::format_to( static_cast<std::byte*>(nullptr), ... );` *does not* compile because of the enable if
`fmt::format_to( static_cast<void*>(nullptr), ... );` *does not* compile
And the latter does not compile not because it's not sfinae friendly "by design", but simply because `std::iterator_traits` tries to form a reference to void.

**Comment by vitaut** [comment] 2021-11-18 18:13
`enable_if` there is an implementation detail, it's not supposed to make `format_to` work in SFINAE context in general. We could probably work this around for iterator but it would be inconsistent with handling other arguments. So the correct fix is to make `fmt::format_to` not discoverable by ADL which you've already done.

**Comment by nuoHep** [comment] 2021-11-18 19:06
> We could probably work this around for iterator but it would be inconsistent with handling other arguments.

It's already inconsistent. In handling of the iterator argument in the presence of pointers to void.

> So the correct fix is to make `fmt::format_to` not discoverable by ADL which you've already done.

The problem is, it worked perfectly fine prior to 8.0, because `fmt::format_to` was not ADL discoverable at all. But 8.0 broke our existing code by causing unwanted ADL via the second argument *and* not being sfinae friendly.
So I'm not really sure what's the "correct" fix here. The rename on our end is already done and was somewhat easy, but I think that `fmt::format_to` should not be ADL discoverable by design (e.g. by making it a ranges style function object). Because the name is generic enough that someone sooner or later may trip up on some ADL  related problem.

**Comment by vitaut** [comment] 2021-11-18 19:13
> It's already inconsistent. In handling of the iterator argument in the presence of pointers to void.

We could strengthen the diagnostic but not relax it i.e. error on more cases.

> fmt::format_to should not be ADL discoverable by design

That's an option too but will be a much bigger breaking change so won't happen any time soon.

Sorry for the breakage.

**Comment by nuoHep** [comment] 2021-11-18 19:21
> > We could probably work this around for iterator but it would be inconsistent with handling other arguments.
> 
> It's already inconsistent. In handling of the iterator argument in the presence of pointers to void.

Also, according to https://en.cppreference.com/w/cpp/utility/format/format_to
```
These overloads participate in overload resolution only if OutputIt satisfies the concept std::output_iterator<const CharT&>.
```
current behavior is inconsistent with `std::format_to`. `std::output_iterator` concept properly handles void pointers and overload resolution rules (read enable_if) are explicit here.

**Comment by vitaut** [comment] 2021-11-18 19:25
> current behavior is inconsistent with std::format_to

That's a good point. We might want to fix one of them =).

**Comment by nuoHep** [comment] 2021-11-18 20:00
Roger, I'll see what I can do
